### ISSUE TITLE
media viewing options for moderators

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#1030]
- [x] all images blurred, with an option to (a) remove blur first 
- [x] all images greyscaled, with an option to (b) remove greyscale (once unblurred)
- [x] all audio muted until selected to unmute
- [ ] #1035

suggestions copied from: https://connect.iftas.org/groups/moderation-tooling/forum/discussion/media-viewing-in-content-review-workflow/

**Comment by mayel** [comment]
Have implemented one simple part:
<img width="1201" alt="Screenshot 2024-10-02 at 21 16 49" src="https://github.com/user-attachments/assets/703b6153-d00e-4c10-8884-c2c75ac3d5ae">
<img width="1252" alt="Screenshot 2024-10-02 at 21 17 01" src="https://github.com/user-attachments/assets/c6495d72-c580-4478-a1a2-329529c531f6">

**Comment by mayel** [comment]
greyscale and muting implemented

**Comment by ThisIsMissEm** [comment]
@mayel what you have implemented with blur is equivalent to what Mastodon currently has, I would love to get Mastodon to a place where I can do greyscaling and other controls, but it means writing a component that's specific for the moderation panel, rather than re-using the component that exists in the web UI.

**Comment by ThisIsMissEm** [comment]
Another thing you could do is keyframes extraction from videos.

Ideally we'd support making a report (at protocol level) about video or audio content and highlighting specific segment(s) of the file to highlight where we want moderators to focus. That'd be something the [SWICG ActivityPub Trust & Safety Taskforce](https://github.com/swicg/activitypub-trust-and-safety/) could look at adding to Flag activities, I think?

**Comment by mayel** [comment]
> making a report (at protocol level) about video or audio content and highlighting specific segment(s) of the file to highlight where we want moderators to focus. That'd be something the [SWICG ActivityPub Trust & Safety Taskforce](https://github.com/swicg/activitypub-trust-and-safety/) could look at adding to Flag activities

Sounds good!

**Comment by mayel** [comment]
Maybe it could be a more general way to refer to a particular timestamp of an object, so it could use d for things other than Flag, e.g. Boost.

**Comment by ThisIsMissEm** [comment]
> Maybe it could be a more general way to refer to a particular timestamp of an object, so it could use d for things other than Flag, e.g. Boost.

Perhaps, though for now I'm focusing on Flag activities, we could increase the domain to all activities later.

**Comment by ThisIsMissEm** [comment]
See here: https://github.com/swicg/activitypub-trust-and-safety/issues/16
