### ISSUE TITLE
Bug Report: Documentation for HACKING.md does not contain install section.

### ISSUE THREAD

**Issue by CSDUMMI** [bonfire-networks/bonfire-app#105]
**Describe the bug**
HACKING.md is missing the [Step 1](https://github.com/bonfire-networks/bonfire-app/blob/main/docs/DEPLOY.md#step-1---download-and-configure-the-app) download and configure section that DEPLOY.md has.

But HACKING.md is not necessarily read after DEPLOY.md and thus the instructions are confusing when first read.

**To Reproduce**
Go to HACKING.md and read it, as if you had not read DEPLOY.md before it.

**Expected behavior**
Either HACKING.md contains the download and configure step too, or another file is created just for this to be read before both HACKING.md and DEPLOY.md

**Additional context**
I've noticed this, while first trying to understand Bonfire and it was quite confusing, because I naturally started with HACKING.md, because I only wanted a testing server to try out Bonfire and not a full deployment.

**Comment by mayel** [comment]
Hi @CSDUMMI and thanks for the report :) I've pushed an update which hopefully addresses what was missing?

**Comment by CSDUMMI** [comment]
Thanks @mayel I think this address it.

Although I'd like it if the docs gave a little more introduction into how an extension is structured and can be developed (as well as an overview of this repository's directories, because I'd not have gotten the idea to look at the `deps` folder for built-in extensions.)

**Comment by mayel** [comment]
Thanks, feel free to open more issues for docs improvement!
