### ISSUE TITLE
Problem: Readme doesn't mention overall status of project

### ISSUE THREAD

**Issue by weex** [bonfire-networks/bonfire-app#107]
Is it testing, alpha, beta? Which features work now and which are in progress?

I've found it's good to be clear about any challenges right from the start to minimize surprises later, in dev setup or install doc sections.

**Comment by mayel** [comment]
Hiya, DEPLOY.md has a warning at the top (I guess we can add it to the main readme too), and otherwise status for flavours and extensions are on the website:
https://bonfirenetworks.org/use-bonfire/ and https://bonfirenetworks.org/extensions/

**Comment by ivanminutillo** [comment]
Thanks @weex we just updated our readme based on your feedback :)
