### ISSUE TITLE
Bug: Posting a message with a tag creates pop-up error

### ISSUE THREAD

**Issue by realkinetix** [bonfire-networks/bonfire-app#1091]
**Describe the bug**
Adding a hashtag to a post causes a pop-up error, and then the UI believes the post hasn't actually submitted correctly, but the post is now actually in the timeline.

**To Reproduce**
Click '+' to create a post
Put a hashtag somewhere in the post

**Expected behavior**
No error popup.

**Bonfire environment (please complete the following information):**
- Running with Docker? (see WITH_DOCKER env variable): No
- Running env: dev
- Running version (check on your instance's homepage): 0.9.10-beta.170 JS en
- Running flavour: classic
- Running any extra/forked extensions: No

**Device (please complete the following information):**
 - Device: Laptop
 - OS: Gentoo
 - Browser: Firefox
 - Browser Version: 128.3.1esr

The returned error that pops up on the screen briefly is:

Sorry, a series of actions could not be completed:
key :name not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a mapkey :name not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map

bonfire_tag 0.1.0: lib/tag.ex:503: Bonfire.Tag.indexing_object_format_name/1
elixir 1.17.3: lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
bonfire_common 0.1.0: lib/utils.ex:657: Bonfire.Common.Utils.maybe_apply/4
bonfire_posts 0.1.0: lib/posts.ex:772: Bonfire.Posts.indexing_object_format/1
bonfire_common 0.1.0: lib/utils.ex:657: Bonfire.Common.Utils.maybe_apply/4
bonfire_search 0.1.0: lib/acts/queue_act.ex:137: Bonfire.Search.Acts.Queue.maybe_index_object/3
bonfire_search 0.1.0: lib/acts/queue_act.ex:57: Bonfire.Search.Acts.Queue.run/2
bonfir

**Comment by mayel** [comment]
Thanks for the report! Should be fixed
