### ISSUE TITLE
Bug: Logged out home page doesn't show recent posts

### ISSUE THREAD

**Issue by realkinetix** [bonfire-networks/bonfire-app#1092]
**Describe the bug**
I can see that both https://campground.bonfire.cafe/ and on my instance there is nothing shown on the home page "Recent activities".

The reason I'm filing this is because there's so much else that is working on the logged-out pages that this seems like an anomaly that could well be working at this point.

**To Reproduce**
Head to http://camground.bonfire.cafe logged out, or perhaps one's own instance and see what shows up when logged out and at the home page.

**Expected behavior**
Recent activities.

**Bonfire environment (please complete the following information):**
- Running with Docker? (see WITH_DOCKER env variable): no
- Running env: dev
- Running version (check on your instance's homepage): 0.9.10-beta.170 JS en
- Running flavour: classic
- Running any extra/forked extensions: No

**Device (please complete the following information):**

 - Device: Laptop
 - OS: Gentoo
 - Browser: Firefox
 - Browser Version: 128.3.1esr

**Comment by mayel** [comment]
Probably related to time_limit feed filter which seems broken recently.
