### ISSUE TITLE
Boundary / ACL improvements

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#114]
- [x] Add ACL name to feed entries (for those permitted to see them, basically authors right now)
- [x] API to list ACLs on an object (to include in FeedActivities queries for example)

**Comment by aschrijver** [comment]
This is just a FYI as I don't know plans wrt ACL's in Bonfire, but I wanted to point out that in terms of federation + ACL's there may be significant downsides. I am not technical full in the loop, but @cwebber is. See: [Solid Community ACL topic](https://forum.solidproject.org/t/spritely-project-the-super-exciting-future-of-fediverse/3470/11?u=aschrijver).

**Comment by jjl** [comment]
ACLs are essentially an instance local structure in bonfire. we will probably end up doing something like OCAP for federation, but it's hard to say.

**Comment by jjl** [comment]
Since controlled became a multimixin, i'm not sure it remains meaningful to display the name of the applied acl, since there are multiple and we are currently using the presets that will later disappear.

**Comment by mayel** [comment]
I think we can still display an indication of public/local-only/custom.

**Comment by mayel** [comment]
done
