### ISSUE TITLE
 The activity preview needs an icon to highlight the boundary selected

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#119]
Currently is always displaied a globe icon. We need to use the specific boundary icon that we have in the create activity boundary dropdown.
![Your-profile-·-Bonfire (3)](https://user-images.githubusercontent.com/1852065/145372055-593c7678-e728-4c2f-8294-a5beda4fdced.png)

**Comment by mayel** [comment]
Depends on https://github.com/bonfire-networks/bonfire-app/issues/114

**Comment by jjl** [comment]
i think we could deal with this by allowing the user to pick an emoji to represent each boundary (with some default suggestions) and treat that as an icon for it

**Comment by mayel** [comment]
done
