### ISSUE TITLE
All 3 tabs (timeline, posts, boosts) in user profile shows the user inbox timeline

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#121]
See 
- https://bonjour.bonfire.cafe/user/ivan/timeline
- https://bonjour.bonfire.cafe/user/ivan/posts
- https://bonjour.bonfire.cafe/user/ivan/boosts

**Comment by mayel** [comment]
Need to fix the relevant functions in FeedActivities once the new new queery lib has been introduced.

**Comment by jjl** [comment]
is there a reason we have the boosts tab? i'm not sure it's a particularly useful thing that deserves such a promiment position.

queery is not coming. the solution here is just to filter by type for 'posts' and 'boosts' pages.

**Comment by ivanminutillo** [comment]
Profile navigation tabs are set as a configuration, so each instance can specify what they want there. 
But I agree boosts are not particular useful. I guess we need to set some default tabs to start with: 
I would pick Timeline, Posts and one among Likes, Media, Boosts 
What do you think?

**Comment by jjl** [comment]
i've always imagined it as containing everything by default, but allowing you to filter which types it contains, perhaps via a dropdown with checkboxes for types?

perhaps we could let users customise which tabs they want to see? with each tab denoting a collection of type filters?

note that this follows the preferences of the viewing user, not the user whose profile is being viewed.

**Comment by jjl** [comment]
i checked what twitter has:

* tweets (basically everything, but doesn't show things that were a reply to someone else's tweet)
* tweets with replies
* media
* likes (tweets they have liked)

**Comment by ivanminutillo** [comment]
Do we want to default to twitter tabs to start with? 
(As new modules will add new activities type, we will need more filters and users being able to show tabs for what they care about)

**Comment by jjl** [comment]
i don't hate them, i guess?

**Comment by mayel** [comment]
I think the idea with the boosts tab was similar to having "tweets with replies" seperately, that replies and boosts are then shown in the default tab. But I like the idea of just having filters on the timeline, and then being able to choose defaults as a user.

**Comment by mayel** [comment]
Also I wouldn't make likes public by default, I find boost serves that purpose better.

**Comment by mayel** [comment]
Which brings up this common behaviour... 
![Screenshot_20211221-072814__01.jpg](https://user-images.githubusercontent.com/115318/146815331-7dc24d87-2d3a-41f7-ac42-d4494dfe3e4a.jpg)

**Comment by jjl** [comment]
i think i would like to see when someone likes or boosts something i've written. but that's for the inbox and is different from showing on the profile.

however, a 'most liked tweets' (or most boosted, whatever)  which is the opposite - things other users have liked, would seem to be more interesting by default.

**Comment by mayel** [comment]
Yeah agreed. In terms of the profile page, it's more about filtering out boosts and replies (which still are shown in your feed if your follow them) and focusing the default view on original posts (and other object types) from that user.

**Comment by jjl** [comment]
for things that are a variation of the outbox, i think they should just be one and you can select what things you want to see (maybe a dropdown to customise, or maybe just some checkboxes or something). for something querying from something else, i think that's worth a tab of its own

**Comment by ivanminutillo** [comment]
Imo the default timeline should show the whole user outbox, other tabs are mostly preferences of which kind of activities the user (or the instance admins) wants to highlight.
I agree Filters are meanigful in the timeline tab to help who is viewing the profile to select what they want to look at

**Comment by mayel** [comment]
fixed
