### ISSUE TITLE
Implement the new thread UX/UI

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#122]
Following https://socialhub.activitypub.rocks/t/discussing-bonfire-thread-ux/2161 decisions

**Comment by mayel** [comment]
The ideas in that thread have implications on db structure, logic and federation schemas which need to be considered before such UX can be implemented...

**Comment by jjl** [comment]
a short, probably inaccurate summary of discussions the three of us just had:

* activitypub essentially imposes a single reply_to for a message
* in bonfire social, we also have this at present
* it seems interesting to permit multiple reply_to. email supported it, but no widely used email software did.
* in a threaded tree view where you could reply to multiple posts, it would become natural to render posts in multiple places, which some people might find confusing.
* there can be many mentions of a post within a post in AP (tags) and in bonfire (edges - tbd which edges)
* perhaps reply_to is just something we have to do for AP purposes and we should use mentions to draw the thread graph?
* this might be a bit startling moving from one fedi software to another if it is too different
* mastodon uses flat threads. to some degree, there isn't much we can do about it at least there.
* sometimes we want to keep track of a particular branch of a discussion (tree threads good for this), sometimes we want to track the whole thread to catch up, or to see how it evolves (flat threads with chronological ordering good for this).
* trees do not really show off the full richness of a directed graph.
* we should prefill mentions so the user can edit them when replying

**Comment by mayel** [comment]
In today's team meeting, we agreed to:

- [x] keep reply_to as a single field (in order to better interoperate with existing ActivityPub apps, and to optionally display a tree UI without repeated replies),
- [ ] also add a one-to-many way to mention other posts so we can have either tree views, image-board style views, or various hybrid approaches

**Comment by ivanminutillo** [comment]
Here a html mockup of new thread UX/UI
https://blissful-yalow-e9e022.netlify.app/src/index.html

**Comment by mayel** [comment]
we can now reply using the form in sidebar
