### ISSUE TITLE
Better Bonfire Social template for logged user

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#125]
As we approach our beta release, it is good to move out from having a UI mostly made to test and experiment features, to a more consolidated one.
The main goal for bonfire social is to release a tool that encourage / empower users to have proper discussions. It should focus on clarity and simplicity,  avoiding distractions like showing data / contents that are not meaningful to the context.  
It has to give the right spaces to let the user articulate their thoughts properly, but also to read & interact with the whole threads.
([Here a dedicated discussion upon Thread UX/UI](https://socialhub.activitypub.rocks/t/discussing-bonfire-thread-ux/2161))
The logged template will be a 3-columns layout, divided in: Sidebar, Main content, widgets.

**Sidebar**: It includes the main action (in bonfire social will be the create/reply to a post action) and the main navigation
**Main section**: It includes the selected view with the primary information (it can be the profile page, a thread, or a timeline)
**Widgets**:  It can include one or more widgets, depending on which page is displaied in the main section.  

Here we will focus on the main bonfire social action: Publish a new post

## Default
![MacBook Pro - 9](https://user-images.githubusercontent.com/1852065/146943818-1059defa-5ea4-4f5a-bd95-2c8c5fdfcfb8.jpg)

Here you have a "publish a new post" form always visible in the sidebar. This gives a a feeling of immediacy and simplicity to publish a new post. The default view will be with the form closed, so the make the whole layout more compact and let the user view the whole navigation list also on 13inch notebooks. 
 
## Open 
![MacBook Pro - 10](https://user-images.githubusercontent.com/1852065/146944099-c2371134-4c52-4262-afb0-350252666d20.jpg)

The space dedicated to write is small, which is fine for sharing small thoughts or links (masto defaults the post maximum length
 to 500chars, while twitter to 240 afaik - in bonfire the default can be set via configuration, but we will likely do not have any limitation as default ?) - but that space does not really incentivize longposts - that's why we have an "expand" icon on the upper right, to let the form cover the whole page     

## Full page
![MacBook Pro - 11](https://user-images.githubusercontent.com/1852065/146944283-b22e1971-0faa-4a32-ae54-8e7d4fa7fea1.jpg)

Here a whole and distraction-free page fully available to write your post, memories, essay, anything you want :)  This page shows up when the user click on the expand icon, and can be closed clicking on the same icon.

**Comment by loid345** [comment]
Maybe at the initial stage it is worth exploring the possibility of visually changing the location blocks in the settings.
