### ISSUE TITLE
When the user unboost an activity, the counter reset to 0 no matter how many other time the activity was boosted 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#128]
The boost counter works fine till I do not unboost the activity, then it gets back to 0.
Here the test: 
https://github.com/bonfire-networks/bonfire_ui_social/blob/main/test/feeds/boosts_activity_test.exs#L49

**Comment by mayel** [comment]
Need to check if that's still the case. And write a test.

**Comment by jjl** [comment]
it no longer happens. there's a new bug to do with deletion, but if anything, it causes the count to be too high, not too low.

i am consulting someone about the views.
