### ISSUE TITLE
Bug: ./config/deps.js.sh: line 6: ./priv/deps.js.sh: Permission denied

### ISSUE THREAD

**Issue by cblock** [bonfire-networks/bonfire-app#131]
**Describe the bug**
`make setup` fails with error `./config/deps.js.sh: line 6: ./priv/deps.js.sh: Permission denied` on a fresh installation after following the guidelines at https://doc.bonfirenetworks.org/hacking.html (Option C)

**To Reproduce**
1. `git clone https://github.com/bonfire-networks/bonfire-app.git bonfire`
2. `cd bonfire`
3. `export FLAVOUR=cooperation`
4. `export MIX_ENV=dev`
5. `export WITH_DOCKER=no`
6. `make pre-config`
7. in config/dev/public.env set `INVITE_ONLY=false`
8. in config/dev/secrets.env set `SECRET_KEY_BASE`, `SIGNING_SALT`, `ENCRYPTION_SALT`, `POSTGRES_USER` and `POSTGRES_PASSWORD`
9. `make setup`

**Expected behavior**
Setup script supposed to finish without errors (i.e. exit code 0)

**Screenshots**
<img width="919" alt="fish__Users_carsten_block_Projects_bonfire" src="https://user-images.githubusercontent.com/230831/147821473-e1cdff71-d701-4ca5-b76b-e99aa75d4966.png">

**Bonfire environment (please complete the following information):**
- Running with Docker? (see WITH_DOCKER env variable): none
- Running env:  dev environmaent, Erlang/OTP 24 [erts-12.1.5], Elixir 1.13.1 (compiled with Erlang/OTP 24),  cargo 1.57.0 (b2e52d7ca 2021-10-21), rustc 1.57.0 (f1edd0429 2021-11-29), postgres (PostgreSQL) 14.1, pnpm 6.24.4, GNU Make 3.81, meilisearch-http 0.24.0
- Running version (check on your instance's homepage): 0.1.0-beta.94
- Running flavour: cooperation
- Running any extra/forked extensions: none

**Device (please complete the following information):**
 - Device: Macbook Air M1 
 - OS: macos 11.6 BigSur
 - Browser N.A.
 - Browser Version N.A.

**Additional context**
`chmod +x priv/deps.js.sh` fixes the problem, i.e. when rerunning`make setup` the error does not reoccur

**Comment by mayel** [comment]
Thanks for the detailed report! Will be adding the chmod command to the makefile to avoid this in future.

**Comment by mayel** [comment]
Fixed
