### ISSUE TITLE
Create a barebones extension as a template that can be used as a base for building new extensions that aren't like existing ones 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#134]

**Comment by ivanminutillo** [comment]
wip here: https://github.com/bonfire-networks/bonfire_extension_template

**Comment by ivanminutillo** [comment]
We may want to add a make task to avoid all the boring steps for finding / replace naming and so on, something like

**Comment by mayel** [comment]
related to #707
