### ISSUE TITLE
UI to handle flags

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#140]
Depends on: #137 #138 #139 #154

**Comment by mayel** [comment]
I've started with a feed of flags at /flags

**Comment by ivanminutillo** [comment]
@mayel I've added the `flag_actions_live` component to render the actions for admins to perform on flagged activities.
I used this workaround on `activity_live.ex` to be able to render them:
```
  def component_actions("flag", _, _), do: [Bonfire.UI.Social.Activity.FlagActionsLive]
```

**Comment by mayel** [comment]
I wired up all flag related views and actions

**Comment by mayel** [comment]
also added DM buttons for the flagger and flagee

**Comment by ivanminutillo** [comment]
done!
