### ISSUE TITLE
Add Topics on github repository

### ISSUE THREAD

**Issue by loid345** [bonfire-networks/bonfire-app#143]
To improve the visibility of the repository, you need to add topics (social-network, activitypub, decentralized, distributed, elixir,  phoenix, phoenix-liveview, etc.). It won't take long
![bonfire topic](https://user-images.githubusercontent.com/20200970/150636647-27ef0e41-34b8-4b91-9f72-a464f29617ef.png)

**Comment by jjl** [comment]
Done
