### ISSUE TITLE
popular tags widget

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#144]
A popular hashtags widget is a quite common and useful feature to include on social networks.
A first iteration could simply show the most popular (with counter for each of them?) 
Also interesting to have the possibility to filter for instance most popular hashtags and fediverse most popular hashtags
![image](https://user-images.githubusercontent.com/1852065/157016734-f09fb0eb-5ef2-4d1a-bdd3-8b44b76660c2.png)

**Comment by mayel** [comment]
This can apply both to hashtags and to other kind of Tags like federated Categories/Topics

**Comment by mayel** [comment]
Doing this for hashtags means we need to record them as in Tag/Tagged DB if we're not already, so they can be counted.
