### ISSUE TITLE
An admin can make other users admin

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#146]

**Comment by mayel** [comment]
Done, and revoke as well:

<img width="489" alt="Screenshot 2022-01-31 at 3 17 58 PM" src="https://user-images.githubusercontent.com/115318/151730354-ab769750-5de5-4d42-8e77-a5cf78615d05.png">
<img width="516" alt="Screenshot 2022-01-31 at 3 18 09 PM" src="https://user-images.githubusercontent.com/115318/151730344-11d687db-57b1-454f-a1d4-5c656567cd4b.png">
