### ISSUE TITLE
As a user I want to know if I have unread/new notifications

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#147]
Focus on the notification icon on header and the notification widget on the left sidebar:
1. The notification icon includes a little circle (as it is on github as well) when the logged user has unseen notifications.
2. The notifiaction widget includes a counter next to the title showing the amount of unseen notifications and they are highligted in the list. User can click on the "mark as read" button to set as seen. Navigate to the notification page will automatically mark all the notifications as seen.
( found this approach to toggle seen status on notification https://elixirforum.com/t/how-to-remove-elements-using-temporary-assigns-and-phx-update/31575/5? )

![notifications](https://user-images.githubusercontent.com/1852065/157015583-8644e686-9517-4848-8ef6-f7fb5eeeaade.png)

**Comment by mayel** [comment]
please expand, does this mean keeping track of read status, does it mean the notification button in navbar changes?

**Comment by ivanminutillo** [comment]
Focus on the notification icon on header and the notification widget on the left sidebar:
1. The notification icon includes a little circle (as it is on github as well) when the logged user has unseen notifications.
2. The notifiaction widget includes a counter next to the title showing the amount of unseen notifications and they are highligted in the list. User can click on the "mark as read" button to set as seen. Navigate to the notification page will automatically mark all the notifications as seen.
( found this approach to toggle seen status on notification https://elixirforum.com/t/how-to-remove-elements-using-temporary-assigns-and-phx-update/31575/5? )

![notifications](https://user-images.githubusercontent.com/1852065/157015583-8644e686-9517-4848-8ef6-f7fb5eeeaade.png)

**Comment by mayel** [comment]
This has been implemented for messages & notifications:
<img width="263" alt="Screenshot 2022-06-05 at 09 33 59" src="https://user-images.githubusercontent.com/115318/172026138-87fe4955-0c8c-4ef9-aa17-d6e4b7a5dd28.png">

Needs still more refining and unit tests, and the counter needs caching.
