### ISSUE TITLE
As a user I want to upload images in my post

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#148]
ckeditor adapter:
https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html

**Comment by ivanminutillo** [comment]
I would opt to move it to backlog for now...

**Comment by antoniskalou** [comment]
Is this still on the backlog?

**Comment by ivanminutillo** [comment]
no, it's part of the social beta features milestone

**Comment by mayel** [comment]
I see you linked to a ckeditor plugin @ivanminutillo. Were you thinking of having it so images are inserted within the text/textarea, or as attachments (like Mastodon does)? 
<img width="280" alt="Screenshot 2022-04-19 at 07 32 45" src="https://user-images.githubusercontent.com/115318/163865654-1f001b81-4afd-469b-9be8-cbfb74348391.png">
<img width="969" alt="Screenshot 2022-04-19 at 07 32 24" src="https://user-images.githubusercontent.com/115318/163865664-4a275466-43c0-4c61-9faf-f345ed2f330d.png">

**Comment by ivanminutillo** [comment]
way better to upload images as attachments also to better control how they're rendered within a post

**Comment by mayel** [comment]
MVP is implemented, still needs design and AP integration work...

**Comment by mayel** [comment]
Incoming and outgoing federation now implemented.
