### ISSUE TITLE
Make sure all string are localisable

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#155]
See https://doc.bonfirenetworks.org/Bonfire.Web.Gettext.Helpers.html#content

**Comment by ivanminutillo** [comment]
I would split this into 2 issues, one technical: Make sure all strings are localisable and a caring one: traslate the UI into at least one language (Which we can invite communities to help us)

**Comment by mayel** [comment]
Sure, though IMO they're dependent on each other, as the simplest way I know of to make sure the technical one is fully done is translating all extracted strings and then checking the app to see that nothing is appearing in English anymore. I'd be happy to to a first pass at French for that.
