### ISSUE TITLE
Create a users directory

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#159]
Related to #215 #217 

- [x] Create a specific route that list all the users that belong to the instance
- [x] Make the user list visible to guests/users/admins, based on a setting in instance config
- [x] Filter user list based on boundary
- [x] Instance-level default discoverability setting controls user being filtered 
- [x] User-level changing of the discoverability setting edits their user profile boundary

**Comment by jjl** [comment]
Because of how things are split up at the moment, it will need to go into bonfire_social (even though it's more of a bonfire_me thing).

it should filter for local users who are public (who you may `:see`, `:read`). the MVP would just be listing ordered by id (i.e. creation date)

**Comment by jjl** [comment]
i would also like to get in here now and add that this is not a feature many instances would want to have at all and it should be easily disabled.

**Comment by KarenKonou** [comment]
Even if an instance has the feature enabled, there should still be an option for users to opt-out individually (mastodon does this for example)

**Comment by edumerco** [comment]
> Create a specific route that list all the users that belong to the instance. 

Good, it should be linked from the admin panel, at least. 

> The route is visible to guest and it will be linked from the homepage

I'm not sure exactly why, but in that case, can a person opt out from the public directory?
