### ISSUE TITLE
Bonfire visual identity (BON-29)

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#16]
Design logo and choose fonts and other visual elements for bonfire branding

**Comment by wakest** [comment]
hey @mayel is there a project branding / visual identity page for Bonfire anywhere ala https://joinmastodon.org/branding

**Comment by mayel** [comment]
@wakest there isn't, what exactly do you need?

**Comment by ivanminutillo** [comment]
We've the logo and branding guidelines, we mostly need to update the screenshots and create the page for it

**Comment by wakest** [comment]
Been slowly working my way through making clean SVG single color icons for all the fediverse server projects I can find: https://joinfediverse.wiki/Fediverse_project_branding as well as trying to pinpoint the most obvious main color of each of the projects. Bonfire sticks out a bit so far as one whos logo doesn't really work well at small sizes, and I also noticed that you use a number of different shades of yellow in different parts of your site so choosing which yellow was most Bonfire-y was a bit hard.

**Comment by ivanminutillo** [comment]
Hey wakest, the official yellow for bonfire is: #fde047
