### ISSUE TITLE
Adding a meaningful preview above the compose form that shows information related which post the logged user is replying to

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#181]

**Comment by ivanminutillo** [comment]
![image](https://user-images.githubusercontent.com/1852065/157019755-d6cf283f-918d-4f7f-8fe7-111f18196947.png)

**Comment by ivanminutillo** [comment]
- [ ] Make the [create activity](https://github.com/bonfire-networks/bonfire_ui_social/blob/main/lib/web/components/create_activity/create_activity_live.ex) component stateful
- [ ] use `send_update` when clicking on reply to send data to the create activity component
- [ ] update the create activity component to show the reply_to box when data arrives

**Comment by mayel** [comment]
<img width="310" alt="Screenshot 2022-04-04 at 15 22 00" src="https://user-images.githubusercontent.com/115318/161468597-be3bd7fb-9fab-4574-b496-7bf40fe8a59f.png">
