### ISSUE TITLE
 Ghost a remote actor (as a user) 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#188]
Related to #201 #197 #138 #139 

- [x] a remote actor that is ghosted by a user shouldn't be included in to/cc/bto/bcc of activities of that user

**Comment by ivanminutillo** [comment]
As a user, it would be good if I see a "blocked" label in the user preview when trying to /switch-user

**Comment by mayel** [comment]
done https://github.com/bonfire-networks/bonfire_federate_activitypub/blob/main/test/boundaries/per_user/mrf/boundaries_ghost_mrf_per_user_test.exs
