### ISSUE TITLE
 Silence an entire remote instance (as a user) 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#195]
Related to #189 #139 #138 #188

- [ ] any actor from an instance that is silenced by a user shouldn't be able to DM or @ mention that user
- [ ] data from a silenced instance should be filtered out of feeds
- [ ] data from a silenced instance should be filtered out of search results

) test does not show in any feeds a Post for an incoming Note from a previously per-user silenced instance (Bonfire.Federate.ActivityPub.Boundaries.SilenceFeedsPerUserTest)
extensions/bonfire_federate_activitypub/test/boundaries/per_user/feeds/instance_silence_in_feeds_per_user_test.exs:79

) test hides a Post in feeds from a remote instance that was per-user silenced later (Bonfire.Federate.ActivityPub.Boundaries.SilenceFeedsPerUserTest)
extensions/bonfire_federate_activitypub/test/boundaries/per_user/feeds/instance_silence_in_feeds_per_user_test.exs:63

**Comment by mayel** [comment]
WIP: https://github.com/bonfire-networks/bonfire_federate_activitypub/blob/main/test/boundaries/per_user/feeds/boundaries_silence_instance_in_feeds_per_user_test.exs

**Comment by ivanminutillo** [comment]
I think for both silencing / ghosting we need to add also a 4# item in the checklist that is about showing the list of silenced / ghosted instances / users in the admin settings

**Comment by mayel** [comment]
already have that: <img width="644" alt="Screenshot 2023-04-20 at 09 44 00" src="https://user-images.githubusercontent.com/115318/233206869-e8abb0eb-66c3-4be6-9421-de2deaf50c0c.png">
