### ISSUE TITLE
Optional display of new activities in feeds

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#204]
Timelines will include a load more button at the bottom to scroll for older contents as well as a load new button at the top if there are newer activities not loaded yet...
![TIMELINE](https://user-images.githubusercontent.com/1852065/157013770-b579e781-0fbc-40a7-9757-3e20b3542f71.png)

**Comment by mayel** [comment]
Related tests to fix: 

  1) test Load More in Threads As a user when I click on load more I want to see next replies below the others (using LiveView websocket) (Bonfire.Social.Threads.LoadMoreTest)
     forks/bonfire_social/test/social_web/threads/thread_load_more_test.exs:62
     Assertion with == failed
     code:  assert Enum.count(replies) == total_posts
     left:  10
     right: 15
     stacktrace:
       forks/bonfire_social/test/social_web/threads/thread_load_more_test.exs:93: (test)

  2) test Load More in Threads As a user when I click on load more I want to see next replies even without JavaScript (using HTTP) (Bonfire.Social.Threads.LoadMoreTest)
     forks/bonfire_social/test/social_web/threads/thread_load_more_test.exs:96
     Assertion with == failed
     code:  assert Enum.count(replies) == total_posts
     left:  10
     right: 15
     stacktrace:
       forks/bonfire_social/test/social_web/threads/thread_load_more_test.exs:126: (test)

**Comment by mayel** [comment]
still need the top button for choosing to display new activities (currently they're dispayed automatically), though you wouldn't want it in some cases, like when you're the one posting
maybe adding a boolean in the pubsub_broadcast, or just checking the subject

**Comment by mayel** [comment]
This should now be easy to implement, in a similar way as we set `hide_activities: "infinite_scroll"` for pre-loading activities which are only displayed when the user clicks the show more button at the bottom.

**Comment by mayel** [comment]
done
