### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#206]
Figma logged users can comment directly on the previews...

### Homepage
https://www.figma.com/proto/nuNA8nATm2rJfjgMHyC0U8/bonfirenetworks?node-id=19%3A2&scaling=scale-down-width&page-id=0%3A1

### Donate
https://www.figma.com/proto/nuNA8nATm2rJfjgMHyC0U8/bonfirenetworks?node-id=38%3A34&scaling=scale-down-width&page-id=0%3A1

### Zappa
https://www.figma.com/proto/nuNA8nATm2rJfjgMHyC0U8/bonfirenetworks?node-id=75%3A2&scaling=scale-down-width&page-id=0%3A1

### Bonfire social
https://www.figma.com/proto/nuNA8nATm2rJfjgMHyC0U8/bonfirenetworks?node-id=91%3A228&scaling=scale-down-width&page-id=0%3A1

**Comment by ivanminutillo** [comment]
I think it can benefit from having 2 different websites:
- 1. bonfirenetworks:  developer-oriented, focused on explaining the bonfire platform, exposing docs, articles, tutorials, roadmaps and anything can help visitors to get their head wrapper around  how to build  with / contribute to the bonfire platform
- 2. joinbonfire: user/communities - oriented, focused on how to join / start a new bonfire instance (avoiding any techy jargons or concept that may be overwhelming to start with ) - with clear call to actions aimed to start using bonfire social, and an overview of bonfire social main value propositions

**Comment by ivanminutillo** [comment]
**joinbonfire landing** : 
![homepage to test (2)](https://user-images.githubusercontent.com/1852065/158015083-170ef4da-86fe-4b96-abd3-c8bda1dfd5fb.png)

**Comment by mayel** [comment]
> developer-oriented, focused on explaining the bonfire platform

I would prefer reframe that as ecosystem-oriented, both in terms of: 
- bonfire ecosystem: info aebout different flavours and extensions available, or how to customise, extend, or build new ones (not just as a developer, but pointing to different options incl. simply opening an issue to propose a feature, etc), and how to contribute (and not just with code!)
- fediverse ecosystem: documenting our implementation of AP, especially extensions to the protocol or schemas, showing checklists of what features/flows have been tested to work with which apps (making it a collaborative effort to test/document/fix interop), links to other resources and tools (eg co-op cloud for deploying bonfire as part of a portfolio of federated and libre tools)
