### ISSUE TITLE
Write a series of user stories to use as guidelines for the zappa extension development 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#209]
Based on [the report](https://whimsical.com/report-DEiDgckNvj6hVvno9au7FP)

**Comment by mayel** [comment]
Four initial user stories have been drafted and published at https://bonfirenetworks.org/zappa/

# Flexible audiences & granular permissions
Users are able to define who can discover, read or interact with them and their content/activities with a granular set of permissions (known as boundaries in bonfire).
[View milestone](https://github.com/bonfire-networks/bonfire-app/milestone/16)

# Opt-in moderation lists for blocked and verified content
Users can create or subscribe to opt-in moderation lists, and - according to permissions - contribute to them. Such opt-in lists may include flagged and blocked content, as well as trusted and verified content.
[View milestone](https://github.com/bonfire-networks/bonfire-app/milestone/28)

# Roles & moderation
The community can decide to decentralise power and responsibility from admins by adding more custom roles to efficiently manage moderation and resolve conflicts.
[View milestone](https://github.com/bonfire-networks/bonfire-app/milestone/26)

# Manual and automatic labelling
Users, moderation list editors, or instance moderators can add labels to content, either by hand or by creating filters for auto-labelling. Labels are shown in feeds to aid with quickly identifying certain aspects of information or misinformation.
[View milestone](https://github.com/bonfire-networks/bonfire-app/milestone/26)
