### ISSUE TITLE
Notification popups need to fade away after 5secs

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#213]
Currently they remain visible on the page till you click them

**Comment by mayel** [comment]
seems complex for such a basic thing, but: https://www.coramsoftware.com/blog/tip-how-to-do-fade-out-flash-hiding/

**Comment by mayel** [comment]
here's an experiment with css-only: https://codepen.io/mayel2b/pen/eYyOPwb

**Comment by mayel** [comment]
done with the `.fade-out` class
