### ISSUE TITLE
Fix UI in Safari

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#220]
the user dropdown doesn't drop down

**Comment by ivanminutillo** [comment]
We need to use a <label tabindex="0"> instead of a <button> on dropdowns made with daisy components because Safari has
[a bug](https://bugs.webkit.org/show_bug.cgi?id=22261) that prevents the button from being focused.

**Comment by mayel** [comment]
dropdown is now working :)

there's also a styling issue when other elements (like label) have type="button"
<img width="1111" alt="Screenshot 2022-03-16 at 12 19 03" src="https://user-images.githubusercontent.com/115318/158487913-5b5d3792-6d48-4d0c-a763-d7a12423820f.png">

**Comment by mayel** [comment]
fixed
