### ISSUE TITLE
Implement a /write route to be used on mobile or to have a distraction-free view

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#221]
- [x] implement Write view
- [x] link from the create activity to the write view and viceversa
- [ ] the content typed in the create activity form should be saved across the different views 
- [ ] If I am replying, I want to see the post details in the write view

**Comment by mayel** [comment]
This should use the same SmartInput / CreateActivity components imo

**Comment by ivanminutillo** [comment]
yes, I'm working on adding more flexibility to the appearance of the smart input and will refactor that later

**Comment by ivanminutillo** [comment]
done!
