### ISSUE TITLE
Flexible boundaries

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#223]
Here some mockups to investigate a simple flow to create and use custom audiences (and other permissions) when publishing a new post:

1. The compose form includes a label highlighting the current boundary applied (based on the current page and preloaded information)
![notifications (1)](https://user-images.githubusercontent.com/1852065/158223959-7bdf448f-f05f-4331-b6be-62b0ad8e18f5.png)

2.  Clicking on it ("anyone can reply" in this case) it opens a modal to perform further customisation. Options includes the default ones: Public, local, note to self, mentioned) plus the user created ones (Memes, Activism, Esperanto, Family&Friends) and the possibility to create a custom one on the fly.
![notifications (2)](https://user-images.githubusercontent.com/1852065/158224151-ac6fc804-9fad-4a8a-a5ab-cb28ac341146.png)
 
## How audiences are created?
1. We have an ad-hoc section in the user settings, to create custom audiences (or reorder the list) to ease the steps when publishing a new post.
The page includes all the user generated list and a cta button to create a new one.
Clicking on the right expand icon on a specifc audience (in this case "memes") it will show a table with the information about which circles / users are included in that audience and the acls applied to each of them.
The user can further refine / edit the audience adding / editing / removing circles or users in it
![notifications (3)](https://user-images.githubusercontent.com/1852065/158225078-b65edd36-b1d6-42b5-b73d-2f6172841aa4.png)

2. The table include the main actions (see, interact, reply, admin (??)): see, interact, admin have an expand icon next to each checkbox.
Clicking on the expand icon next to a checkbox, it will show all the single actions included in that group (eg Interact includes: like, follow, boost, mention) so to have a more fine grained control over each specific action a circle/user can perform
  ![notifications (4)](https://user-images.githubusercontent.com/1852065/158225541-1fe94183-b2b2-4531-b81d-09324a61076a.png)

**Comment by dajbelshaw** [comment]
This is great! My only feedback is based on UX and semantics (as ever!)

1. 'Lists' is a more neutral and already-accepted term than 'audiences' (which suggests a performance, and is more ambiguous)
2. Presenting the user with so many options in screenshot 2 will baffle them, so I would suggest that this appears after clicking the 'Lists' (currently 'Audiences') option 
3. What's the use case for 'Note to self'? A social network doesn't feel like a place for notes to oneself?*

\* *I know chat apps have this, and I use the functionality in Signal regularly, but that's to transfer files privately between mobile and desktop. Is that the idea here?*

**Comment by ivanminutillo** [comment]
Thanks Doug, I'm working on the updated mockups today and hope to share something soon

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ivanminutillo** [comment]
Updating the issue with the latest mockups:


![notifications (2) (1)](https://user-images.githubusercontent.com/1852065/177858268-ecfef9c0-8ace-44ef-a979-2d3b10bf5994.png)

![Frame 27 (1)](https://user-images.githubusercontent.com/1852065/177858346-ee23deb0-9097-441d-8bc3-1132263fde8d.png)
![Frame 28 (1)](https://user-images.githubusercontent.com/1852065/177858378-073db7c8-21c4-4ea6-b5a9-a91be84c9218.png)
![Frame 26 (1) (1)](https://user-images.githubusercontent.com/1852065/177858364-80ac5c2e-a0e1-48a7-9877-969709bd369d.png)

**Comment by mayel** [comment]
- [ ] make tagify work
- [ ] improve accessibility
- [ ] button to edit cirles on the boundary edit view
- [ ] highlight the boundaries selected in list
- [ ] create a new boundary from modal
- [ ] delete should have confirmation modal

- [ ] adding the ability to create a circle from modal
- [ ] hide public/local/mentions when you edit a boundary in modal
- [ ] boundary settings should stay in modal
- [ ] make public/local/mentions be mutually exclusive

- [ ] show flash error message when trying to perform something not allowed (eg. boost, like)
- [ ] show flash error message instead of opening the smart input when clicking the reply button if not allowed
- [ ] boundaries not taken into account when you post
- [ ] filter out more preset boundaries from modal list
- [ ] maybe archive circle/boundary instead of delete

**Comment by ivanminutillo** [comment]
Some more issues
- [ ] when a new user/circle is added to the boundary, first time the user click on a permission, it does not trigger the action (it does from the 2# time)
- [ ] users added to existing boundary should inherit the existing acls
- [ ] if I add a user to a boundary and I do not edit any boundary, the addition is not saved (which may makes sense operational, but it's a wrong UX)

**Comment by mayel** [comment]
Done for now. Incomplete checkboxes will have to be copied to a new issue.
