### ISSUE TITLE
Editable instance legals

### ISSUE THREAD

**Issue by jjl** [bonfire-networks/bonfire-app#236]
* [x] Code of conduct / Terms of use
* [x] Privacy Policy

**Comment by mayel** [comment]
<img width="908" alt="Screenshot 2022-04-18 at 15 46 24" src="https://user-images.githubusercontent.com/115318/163751325-11902402-0b52-40a1-a185-e1cf8d99222d.png">
<img width="854" alt="Screenshot 2022-04-18 at 15 45 50" src="https://user-images.githubusercontent.com/115318/163751363-68d2eed0-8529-492d-88a8-6189b974f4c0.png">
