### ISSUE TITLE
Bug: ArgumentError when trying to block an anonymous user

### ISSUE THREAD

**Issue by antoniskalou** [bonfire-networks/bonfire-app#249]
**Describe the bug**
ArgumentError when trying to block an anonymous user

**To Reproduce**
1. Create an anonymous post (not sure how I did that)
2. Click on "Block this user"

**Expected behavior**
Not sure, how do you even block an anonymous user?

**Comment by mayel** [comment]
There's no anonymous posts, so that was a bug (probably the creator/subject not being queried or displayed correctly)
