### ISSUE TITLE
Refactor to remove circular dependencies

### ISSUE THREAD

**Issue by antoniskalou** [bonfire-networks/bonfire-app#250]
We have some circular dependencies that eventually need to be resolved.

Examples:
- Bonfire.Me <-> Bonfire.UI.Social
- Bonfire.Social <-> Bonfire.UI.Social

This seems to be mostly an issue with UI code being moved up to business logic code.

**Comment by fcevado** [comment]
is someone already taking care of that?
is there a list of repositories that should depend on `Bonfire.UI.Social`?
as a starting point, this [search](https://github.com/search?q=org%3Abonfire-networks+bonfire_ui_social&type=code) shows every metion to `bonfire_ui_social`.
repositories with `bonfire_ui_social` in their `deps.git` would be:
- bonfire_invite_link
- bonfire_recyclapp
- bonfire_search
- bonfire_me
- bonfire_ui_valueflows
- bonfire_ui_coordination

I would assume the two ui repos are supposed to depend on `bonfire_ui_social` :thinking:

**Comment by mayel** [comment]
👋 Thanks for looking at this!

We've been wanting to do a rethink and heavy refactor of what code goes in what repo (while we can without causing too much pain before the beta release). 

For example, currently the feature repos `bonfire_me` and `bonfire_social` contain LiveViews that contain no HTML, instead embedding a Component from `bonfire_ui_social`, which in turn embeds more components. 

This is different to the approach taken for `bonfire_ui_coordination`, `bonfire_ui_kanban` and `bonfire_breadpub` (the last of which should probably be renamed for consistency), which contain LiveViews and some bespoke components, and embed reusable components from `bonfire_ui_valueflows` and `bonfire_ui_social`.

So maybe something similar would make more sense (having in mind that we want extensions and features to be easily "forkable" so people can customise or replace them):

- bonfire_me / bonfire_social: contain contexts
- bonfire_ui_me / bonfire_ui_social: contain views and any components used only in that extension
- bonfire_ui_common: contain components used by several UI extensions

How does that sound? Would be great to talk this through before we go through with it (which I'll be happy to do myself as it will be mostly moving files around and renaming modules, and knowledge of the codebase will probably make it an easier job)...

**Comment by fcevado** [comment]
I guess a initial step could be just resolve the circular dependencies. so just take care of `bonfire_ui_me` and `bonfire_ui_social`. make everything that uses the UI components of `bonfire_me` and `bonfire_social` starting using their ui counterparts. Once that is solved it probably gonna end up with some duplication that could be centered in a future refactor for the ui components library. :thinking:

**Comment by mayel** [comment]
Yeah I'd say splitting the current `bonfire_ui_social` into `bonfire_ui_shared_components`, `bonfire_me_social` and `bonfire_ui_social` would be the first step.

**Comment by mayel** [comment]
This has now been done:

-     bonfire_me / bonfire_social: contain contexts
-     bonfire_ui_me / bonfire_ui_social: contain views and any components used only in the corresponding extension (as well as LiveHandlers)
-     bonfire_ui_common: contain components used by several UI extensions
