### ISSUE TITLE
When I boost an activity, I see a wrong live update component

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#252]
This happen with live_update, once I refresh the page I saw the correct component.
<img width="589" alt="Screenshot 2022-04-05 at 14 16 13" src="https://user-images.githubusercontent.com/1852065/161751678-af952efa-ecdf-4a31-9df7-273672177f20.png">

**Comment by mayel** [comment]
Duplicate of #265
