### ISSUE TITLE
The activity that shows I followed someone miss some data

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#253]
<img width="582" alt="Screenshot 2022-04-05 at 14 17 32" src="https://user-images.githubusercontent.com/1852065/161751875-29ce580b-54d4-4bf1-a600-3baf433ab346.png">

**Comment by antoniskalou** [comment]
<img width="433" alt="Capture" src="https://user-images.githubusercontent.com/51527605/165081423-1f001d6d-bd98-400b-97bd-bd531f140046.PNG">
