### ISSUE TITLE
When I create a reply from timeline, the updated timeline activity does not show the parent post

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#254]
**when live_updating:**
<img width="586" alt="Screenshot 2022-04-05 at 14 22 02" src="https://user-images.githubusercontent.com/1852065/161752531-df320d06-54d8-4fda-bea2-183107443995.png">

**after a refresh**
<img width="590" alt="Screenshot 2022-04-05 at 14 22 18" src="https://user-images.githubusercontent.com/1852065/161752588-8cc281c0-d4b1-4486-b327-ea19b05eeeb1.png">

**Comment by mayel** [comment]
fixed
