### ISSUE TITLE
When unboosting an activity, it returns an error and the timeline is not correctly updated

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#256]
<img width="668" alt="Screenshot 2022-04-05 at 14 27 46" src="https://user-images.githubusercontent.com/1852065/161753527-0ffbe250-b549-49f4-8313-81ddac7c3c7e.png">

**Comment by antoniskalou** [comment]
Error message was because of `unboost` returning `[..]` instead of `{:ok, [..]}` and then `Common.undead_error` handling plain values (without `{:ok, val}`), causing it to show the error above.

**Comment by antoniskalou** [comment]
Note, the boost isn't removed until refresh.
