### ISSUE TITLE
Boosting an activity in the thread view does not automatically update the icon status

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#258]
Clicking on the boost icon, it does not change its color untill an hard refresh

**Comment by antoniskalou** [comment]
Before refresh:
<img width="445" alt="before_refresh" src="https://user-images.githubusercontent.com/51527605/165513619-631f5a10-cad0-426e-b975-eaa55472f932.PNG">

After refresh:
<img width="431" alt="after_refresh" src="https://user-images.githubusercontent.com/51527605/165513651-4fb66a9b-958d-4149-80d1-598a339a51e0.PNG">

**Comment by mayel** [comment]
Related tests:

 15) test boost a post and it appears on my feed (Bonfire.Social.Activities.BoostPost.Test)
     forks/bonfire_social/test/social_web/activities/boost_post_test.exs:12
     Assertion with =~ failed
     code:  `assert view |> element(".feed [data-id='boost_action]") |> render_click() |> Floki.text() =~ "Boosted"
     left:  "\n      Search\n    FeedsNotificationsMessagesLikes / FavouritesCristobal Nienow@hilton2003\n    My Profile\n  \n    Switch User\n  \n    Settings\n  \n    Welcome\n  \n    Logout\n  Go backTitleDescription\nPublicLocalMentionsMessageCustomPublicPublicly visible to everyone on the fediverse and in search enginesLocal InstanceVisible to all members of this instanceMentionsVisible only those mentioned, across the fediverseMessageVisible only to people included in this message thread: \n        \n        CW\n      Post\n    \n                  Menu\n                Close panelCristobal Nienow@hilton20030\n                    Followers\n                  0\n                    Following\n                  \n                    Profile\n                  \n                    Switch User\n                  \n                    Direct Messages\n                  \n                    Settings\n                  \n                    Home\n                  \n                  Logout\n                Local\n          Pete Larkin\n        @roxane_wolff·\n        1 second ago\n      \n      here is an epic html post\n\n    \n    Boost\n    \n      Like\n      \n      Follow Pete Larkin Flag this Post Flag  Pete Larkin\n          Block Pete Larkin \n        Popular hashtags#eurovision122 post#eurovision122 post#eurovision122 post#eurovision122 post#eurovision122 post#eurovision122 postCloseCancel"`
     right: "Boosted"
     stacktrace:
       forks/bonfire_social/test/social_web/activities/boost_post_test.exs:24: (test)

**Comment by mayel** [comment]
Also because boost causes an extra activity to show in feed, need to figure out how to avoid this test failure:

 10) test unboost a post works (Bonfire.Social.Activities.BoostPost.Test)
     forks/bonfire_social/test/social_web/activities/boost_post_test.exs:42
     ** (ArgumentError) selector ".feed article:first-child() button[data-id='boost_action]" returned 2 elements and 2 of them matched the text filter "Boosted":

**Comment by ivanminutillo** [comment]
could it be a bug in this function: 
```
def send_updates(component_module, object_id, assigns) do
    debug("ComponentID: try to send_updates to #{component_module} for object id #{object_id}")
    IO.inspect(assigns, label: "teeeeeeeeeeeeeeeeeeeeeeeee")

    for component_id <- ids(component_module, object_id) do
      debug("ComponentID: try stateful component with ID #{component_id}")
      Phoenix.LiveView.send_update(component_module, [id: component_id] ++ assigns)
    end
  end
  ```
  
  which it does not address the right components to update?

**Comment by mayel** [comment]
That function sends an update to all stateful components in the current view that have been created using `ComponentID.new(component_module, object_id)`, so it would be both...

**Comment by mayel** [comment]
The thing is that we also have an unusual behaviour in that you are able to boost something several times, so actually it makes sense for only the boost button on the actual boost activity to be an unboost button.

**Comment by mayel** [comment]
fixed
