### ISSUE TITLE
When i reply in the thread page, the other replies disappear and they only re-appear in the right order after an hard refresh

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#259]
**the thread page before adding a reply**
<img width="1280" alt="Screenshot 2022-04-05 at 14 34 43" src="https://user-images.githubusercontent.com/1852065/161754620-24fb130b-ee3d-43bf-85f8-1b73d88102ea.png">

**the thread page updated live**
<img width="1258" alt="Screenshot 2022-04-05 at 14 35 05" src="https://user-images.githubusercontent.com/1852065/161754662-d19a6c4c-1955-4954-9879-9d66e974d426.png">

**the thread page after an hard refresh**
<img width="1260" alt="Screenshot 2022-04-05 at 14 35 20" src="https://user-images.githubusercontent.com/1852065/161754698-6e9f3a4c-53b1-4ad8-b09a-dfbbb39b829d.png">

**Comment by mayel** [comment]
This is the kind of error appearing in console when this happens `[error] EctoMaterializedPath: there may be a mising or invalid `path`, resulting in a different count of items (3 vs 1) meaning those with ids [01G1M02CQGRTG8Z5BX6HMV8VW5, 01G1M021M7NA6YY634VEMVDEKM] can't be arranged`

**Comment by mayel** [comment]
fixed
