### ISSUE TITLE
My likes tab in (current user) profile

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#262]

**Comment by mayel** [comment]
I'd like likes being public or not to be a user preferences (with a default set in instance config), in which case we need another place to access them (not use more like bookmarking).

**Comment by ivanminutillo** [comment]
why not leaving it in the profile tab and show or not for other users based on preferences?

**Comment by mayel** [comment]
Wouldn't it be confusing? Visiting your profile should give you an idea of what others can see.
