### ISSUE TITLE
[ckEditor extension] JS error with ckeditor: Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#271]
This bug is preventing us to use the smart input correctly

**Comment by mayel** [comment]
I see that the error comes from the emoji picker: http://localhost:4000/deps/bonfire_editor_ck/assets/js/ckeditor/build/webpack:/BalloonEditor/node_modules/emoji-picker-element/database.js
