### ISSUE TITLE
Add counters to likes / boosts / replies actions 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#272]
We may want to add also a configuration in admin and user settings to show/hide the counters from the UI

**Comment by ivanminutillo** [comment]
@mayel do we want to show counters only on the main thread activity (that should be already doable) for the purpose of beta?

**Comment by mayel** [comment]
The display of counts (for follows/likes/boosts...) has now been made optional, with settings key `[:ui, :show_activity_counts]`
