### ISSUE TITLE
When replying to an activity that contains a tag, the smart input adds an empty "@" character at the beginning

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#293]
![image](https://user-images.githubusercontent.com/1852065/167374649-11500ed0-6783-41da-9f51-fc0a86553486.png)

**Comment by ivanminutillo** [comment]
@mayel I guess somewhere here https://github.com/bonfire-networks/bonfire_social/blob/main/lib/social/threads.ex#L175 we need to add a condition to not include hashtags

**Comment by mayel** [comment]
ah yes, makes sense!
