### ISSUE TITLE
When i create a reply in discussion, the instant update shows also the parent comment

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#301]
it should not show the original comment if you are in the discussion page, only the reply below the right comment
<img width="606" alt="Screenshot 2022-05-17 at 23 02 38" src="https://user-images.githubusercontent.com/1852065/168909706-816159f8-a379-469b-bdf8-d11496729b5e.png">

**Comment by mayel** [comment]
not happening anymore
