### ISSUE TITLE
Reply to a post may return an unexpected error: "epic was not completed: Post content: Html body: can't be blank" 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#315]
Need to investigate when it happens

**Comment by mayel** [comment]
Adding a browser based automated test for this

**Comment by mayel** [comment]
seems to be working now?

**Comment by ivanminutillo** [comment]
still some edge cases, was looking into it

**Comment by mayel** [comment]
done https://github.com/bonfire-networks/bonfire_ui_social/commit/f89f4eb570af3957573de533da589ed710fec0c8
