### ISSUE TITLE
Screenshots for various features/url

### ISSUE THREAD

**Issue by cvkmohan** [bonfire-networks/bonfire-app#356]
This is certainly not an issue/bug. I thought a few screenshots of the app will do great help for an enthusiast. It might help the following class of audience:
1. Community Owners. They might be slightly non-technical and screenshots may provide a quick overview for them.
2. Even Developers. The non-docker installation of development environment is looking quite involved. May be the screenshots might catch the attention.

May be the important UI url can be kept in a text file - and - with every small release - the screenshots can be captured and updated. Just a thought.

**Comment by mayel** [comment]
Good point thanks! We're planning to add a few screenshots and screencasts to the website for the beta release.

**Comment by mayel** [comment]
There's a screenshot in this blog post, and a screencast and more coming soon: https://bonfirenetworks.org/posts/beta_what_to_expect/
