### ISSUE TITLE
Quick UI suggestion, move topbar in the header to sidebar

### ISSUE THREAD

**Issue by Freeplayg** [bonfire-networks/bonfire-app#362]
Maybe move that topbar menu to the sidebar menu, as well? More vertical space for the timeline, and it just seems to make sense for the navigation.
![image](https://user-images.githubusercontent.com/40742947/174914336-1cfbf1e7-cbeb-4cb9-9c18-b64aa8b33ba8.png)

**Comment by Freeplayg** [comment]
Yay! I just think it would be best since we should get every bit of vertical space. Since monitors are getting wider and there's still that dreaded 768p resolution, lol.

**Comment by Freeplayg** [comment]
Maybe possibly an option to also move that nav header to the side, as well? Like in my Masto Modern theme: 
![image](https://user-images.githubusercontent.com/40742947/175833959-67e1bd8e-b695-42e1-96d0-8fccf078b9a4.png)

**Comment by mayel** [comment]
Yeah I'd like to have that option too, though maybe moving it to the left sidebar? so the left could be global widgets and navigation and the right can be contextual ones (based on what's in the center)?

**Comment by Freeplayg** [comment]
I was sort of thinking something like these maybe? (quickly made in inspect element)
![image](https://user-images.githubusercontent.com/40742947/176254953-924a6ea5-2bd5-4af6-a7f1-745ca078654c.png)
![Screenshot from 2022-06-28 14-21-12](https://user-images.githubusercontent.com/40742947/176254971-ee776a35-b7fe-49e4-994c-09658bd97153.png)

**Comment by Freeplayg** [comment]
> if so, I'd avoid having the composer box opened by default, but make it expand on click to save space, like this: ![notifications (8)](https://user-images.githubusercontent.com/1852065/176143238-b1b264ba-9a68-47e8-ba1a-70557d3f76ee.png)
> 
> (interesting also so that you can switch between different activity types from the grid icon)

I feel like if you were to go with this sort of design, I would just make the compose box a button.

**Comment by ivanminutillo** [comment]
Thanks for the discussion and feedbacks @Freeplayg , we updated our main layout:
- we merged the 2 navigations in just one left sidebar
- we added a configuration to switch between the composer box in the sidebar to a button that opens a composer in the bottom right of the screen

## Email like composer
![image](https://user-images.githubusercontent.com/1852065/179459075-e4d42a9c-0d6d-4804-b5b3-75b35201c545.png)

## Microblogging composer 
![image](https://user-images.githubusercontent.com/1852065/179459420-ca09c174-3b8b-4eea-9ca6-8bb73647d5b2.png)

We will release the new layout in the next days :)
