### ISSUE TITLE
Bug: reply activity dissappears from smart input when a live update comes in

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#367]
when composing a post reply and a notification comes in, the frontend refreshes and the "reply to" post is cleared. Can be reattached though, by clicking on the reply arrow once more. Posts field is kept open and post text is saved.

See https://playground.bonfire.cafe/post/01G6D088BYTZ7X8MTKTAV96VJ2#

**Comment by ivanminutillo** [comment]
fixed
