### ISSUE TITLE
Improve the readability of nested threads

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#382]
### Current issue:
![image](https://user-images.githubusercontent.com/1852065/175769323-592fd2af-c0a0-4460-8063-665e1e28a92f.png)

#### Current Suggestions:
- reduce the left padding to increase the space of the whole activity
- add horizontal scrolling 
- enable full screen mode

**Comment by Freeplayg** [comment]
Another thing

The replies should only indent when there are multiple replies

So if there's only one reply to each one, it would be a straight line down instead of indenting every single reply
