### ISSUE TITLE
Bug: code block in replied widget above the smart input break the composer ui

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#385]
On desktop at least (Firefox 101, screen of 1360x768), when replying to a message with a loooong code block in it, the entire reply UI gets slightly more and more hidden towards the left of the screen, with a part of the text and button disappearing, and there is no way of scrolling back.

This doesn't happen in full screen writing mode, though.

**Comment by mayel** [comment]
Same if you paste a long URL, the submit button disappears to the right.
