### ISSUE TITLE
Font size is too small in compose window

### ISSUE THREAD

**Issue by dajbelshaw** [bonfire-networks/bonfire-app#388]
![Screenshot 2022-06-25 17 35 19](https://user-images.githubusercontent.com/2429426/175782701-3fe9484e-5287-4540-8a22-557094a83ee2.png)

https://playground.bonfire.cafe/post/01G6DV9HJWVJN7XVPT18Z36319#

**Comment by mayel** [comment]
I increased it slightly, but we can review that when designing the new compose UI (as it will have more space).
