### ISSUE TITLE
Allow users to edit or 'delete and redraft' posts

### ISSUE THREAD

**Issue by dajbelshaw** [bonfire-networks/bonfire-app#390]
![Screenshot 2022-06-25 17 55 45](https://user-images.githubusercontent.com/2429426/175783312-7342e2ba-4cd0-462f-8840-fe8626bbb7af.png)

https://playground.bonfire.cafe/post/01G6DFKN99SCWSD7C71V0NAMBC
#

**Comment by mayel** [comment]
Added to changemap here: https://changemap.co/bonfire/bonfire/task/6510-enable-deleteredraft-or-edit-of-posts/

**Comment by mayel** [comment]
Possible libraries that can do the heavy lifting of version tracking:
https://hexdocs.pm/ex_audit/readme.html
https://github.com/izelnakri/paper_trail
