### ISSUE TITLE
Allow us to scroll from anywhere

### ISSUE THREAD

**Issue by Freeplayg** [bonfire-networks/bonfire-app#391]
Having to hover the mouse over the timeline to scroll through it is a bit annoying. Would be better if we could have regular overflowing from the body and having the sidebars use `position: sticky;` (https://developer.mozilla.org/en-US/docs/Web/CSS/position)

**Comment by ivanminutillo** [comment]
Thanks, just implemented this behaviour - it will be implemented from the next release :)
