### ISSUE TITLE
Feature Proposal: Combine duplicate posts

### ISSUE THREAD

**Issue by Freeplayg** [bonfire-networks/bonfire-app#396]
**Is your feature request related to a problem? Please describe.**
Would help not clog the timeline as much if posts weren't shown multiple times, maybe due to a favorite or repost, like shown here:
![image](https://user-images.githubusercontent.com/40742947/175820561-5852c518-f6c2-48b1-84c7-bb68c49667c7.png)

**Describe the solution you'd like**
Combine those posts, if there are multiple interactions, maybe say something like "User, User, and more reposted"

Not sure of any alternatives.

**Comment by mayel** [comment]
This is now implemented, at least for some cases where duplicates were shown.

**Comment by loid345** [comment]
I would like to hear @josevalim opinion about the project
