### ISSUE TITLE
Bug: Tabbing in compose box prevents me from tabbing out

### ISSUE THREAD

**Issue by Freeplayg** [bonfire-networks/bonfire-app#401]
**Describe the bug**
When you tab into the box, there is no way of exiting the box, because tabbing indents

**To Reproduce**
1. Go to any page with the compose box
2. Tab into the compose box
3. Become stuck.
4. oh no

**Expected behavior**
Let the user tab out

**Screenshots**

https://user-images.githubusercontent.com/40742947/176046964-6e2ff9a4-40f4-4a8e-917d-c6db5769ca03.mp4

**Bonfire environment (please complete the following information):**
Bonfire playground instance.

**Device (please complete the following information):**
 - Device: Laptop
 - OS: Fedora 36
 - Browser Firefox
 - Browser 101.0.1

**Additional context**
I'm sure you guys are working more on accessibility like better navigation of posts and timelines, just might be something that may be overlooked

**Comment by ivanminutillo** [comment]
fixed in the new release
