### ISSUE TITLE
Define & implement granular role & permission system for instance administration and moderation

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#406]
I think we can have user-defined roles (instance-wide roles for now, but in future they could apply to a group or organisation) by defining a global boundary (eg. Moderation), and assign roles using circles (eg. Instance Mods). 

In order to use boundaries to control permissions of instance admin and moderation actions, we'd need to add verbs to the app (on top of the existing ones listed below).

The reason for using verbs is that our boundary system works by linking a scope (eg. user/circle/instance) to a boundary, which is defined as a verb and a value of `true` (= grant permission, unless forbidden elsewhere), `false` (= forbid) or `undefined`. 

Here are some ideas: 
- block: manage instance-wide blocks
- mediate: see flags and message the people involved to attempt resolution
- mitigate: lock-down the boundaries of things as part of moderation (eg. lock commenting, make private, etc)
- toggle: enable/disable extensions or features
- describe: edit info (eg, instance name/description/images)
- decorate: manage themes, fonts, etc
- localise: manage localisation / languages 
- mandate: edit terms like code of conduct
- configure: change general settings
- grant: edit global boundaries 
- appoint: give roles to others
- invite: invite users 
- admit: review/approve join requests
- observe: view stats
- investigate: view logs
- administer: all of the above

Suggestions welcome!

Here are existing verbs already implemented in boundaries (I have noted ones where ActivityPub uses a different term, which we may want to adopt instead):
- Tag
- Request
- Reply
- Message
- Mention
- [Read](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-read)
- [Like](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-like)
- [Follow](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-follow)
- [Flag](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-flag)
- [Delete](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-delete)
- [Create](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-create)
- Edit --> [Update](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-update)
- See --> [View](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-view)
- Boost --> [Announce](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-announce)

Extra ActivityPub verbs we may also want to add (or use instead of above ideas, if any of them can fit):
- [Accept](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-accept)
- [Add](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-add)
- [Arrive](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-arrive)
- [Block](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-block)
- [Dislike](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-dislike)
- [Ignore](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-ignore)
- [Invite](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-invite)
- [Join](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-join)
- [Leave](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-leave)
- [Listen](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-listen)
- [Move](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-move)
- [Offer](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-offer)
- [Question](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-question)
- [Reject](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-reject)
- [Remove](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-remove)
- [TentativeReject](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tentativereject)
- [TentativeAccept](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tentativeaccept)
- [Travel](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-travel)
- [Undo](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-undo)

**Comment by dajbelshaw** [comment]
The only useful feedback I have here is to avoid words that sound and look very similar (in English, at least) - e.g.
* mandate
* mediate
* mitigate

It's easy for people to get confused, including admins, with not-great consequences...

**Comment by mayel** [comment]
Pushed an initial implementation, starting with these verbs:
```
      toggle: %{id: "1CANENAB1E0RD1SAB1EFEATVRE", verb: "Toggle", icon: Boxicon.Regular.ToggleRight, summary: "enable/disable extensions or features"},
      describe: %{id: "1CANADD0M0D1FY1NF0METADATA", verb: "Describe", icon: Boxicon.Regular.CommentEdit, summary: "Edit info and metadata, eg. thread titles"},
      grant: %{id: "1T0ADDED1TREM0VEB0VNDAR1ES", verb: "Grant", icon: Boxicon.Regular.Key, summary: "Add, edit or remove boundaries"},
      appoint: %{id: "1T0ADDC1RC1ES0RASS1GNR01ES", verb: "Appoint", icon: Boxicon.Solid.UserBadge, summary: "Add to circles or assign roles"},
      invite: %{id: "11NV1TESPE0P1E0RGRANTENTRY", verb: "Invite", icon: Boxicon.Regular.Gift, summary: "Invite users or grant entry"},
      mediate: %{id: "1T0SEEF1AGSANDMAKETHEPEACE", verb: "Mediate", icon: Boxicon.Solid.FlagCheckered, summary: "See flags"},
      block: %{id: "1T0MANAGEB10CKGH0STS11ENCE", verb: "Block", icon: Boxicon.Regular.Block, summary: "Manage blocks"},
      configure: %{id: "1T0C0NF1GVREGENERA1SETT1NG", verb: "Configure", icon: Heroicons.Solid.AdjustmentsIcon, summary: "Change general settings"}
```
