### ISSUE TITLE
Browse topics

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#421]
First mockups for topics: 
![image](https://user-images.githubusercontent.com/1852065/180268375-e03a6738-9345-41e8-8a44-545e0e9c3123.png)
We could have also 2 widgets: subscribed topics on the left sidebar (below the main navigation) and popular topics on the right one 
The topic page resembles the user profile one, but more focused on content, in a next step we can provide an option to show content in a more editorial way (moving away from timeline based posts)
we need 2 more pages: 
- team page: (available to all) to see who have editorial permissions over the topic
- settings page (available to topic team members) to edit the topic (based on permissions)

**Comment by mayel** [comment]
Very nice! I guess compose a post here would post in the topic (if you have permission to)?

I'd also like to see the ability to browse sub-topics or related topics, and to create new ones (depending on boundaries)...
