### ISSUE TITLE
Topic activity preview

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#422]

**Comment by ivanminutillo** [comment]
![image](https://user-images.githubusercontent.com/1852065/180655622-5df1a920-c3a7-46ea-9ace-805eaafd4be1.png)

TODO: 
- [ ] since the topic is an actor and can publish things, it should likely have an avatar/image
- [ ] Activity preview actions:
  - View topic
  - Subscribe
  - More
  - ...

**Comment by mayel** [comment]
> since the topic is an actor and can publish things, it should likely have an avatar/image

the topic won't publish things directly, but only boost things from regular users, so I don't think the avatar is a requirement (at least in bonfire we don't show the avatar of the booster)
