### ISSUE TITLE
Feature Proposal: Use prefers-color-scheme

### ISSUE THREAD

**Issue by Freeplayg** [bonfire-networks/bonfire-app#451]
**Is your feature request related to a problem? Please describe.**
Sometimes I switch between light and dark mode on my desktop, and want the site to follow that

**Describe the solution you'd like**
Using prefers-color-scheme, preferably something similar to Misskey's theme switcher:
![image](https://user-images.githubusercontent.com/40742947/192113998-f0aa4fc3-0b6e-4db8-96e8-1c1ed2eab54a.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme 
https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

**Comment by mayel** [comment]
Good idea, thing is we don't have just one dark and one light theme. Maybe we should have a user setting a preferred dark theme and a preferred light theme if the "sync / auto" option is on?

**Comment by mayel** [comment]
> Maybe we should have a user setting a preferred dark theme and a preferred light theme if the "sync / auto" option is on?

Ah lol, just noticed that's what is done in the screenshot 👍

**Comment by mayel** [comment]
Done:
https://user-images.githubusercontent.com/115318/192189495-7892c6c6-123d-46b8-a5d3-6ede236bd98e.mov
