### ISSUE TITLE
Feature Proposal: Show tooltips in sidebar

### ISSUE THREAD

**Issue by Freeplayg** [bonfire-networks/bonfire-app#454]
**Is your feature request related to a problem? Please describe.**
Minor thing but, Most people won't know what these icons mean, unless they click to open it or the sidebar

![image](https://user-images.githubusercontent.com/40742947/193461531-c8ffbcca-a1f6-48fe-acbc-2ffb55a43113.png)

**Describe the solution you'd like** 
Showing tooltips on hover

**Comment by Ryuno-Ki** [comment]
As alternative, I would suggest to add a word under each one.

**Comment by ivanminutillo** [comment]
closing because that's not relevant anymore as the new UI does not include that sidebar to switch between app anymore
