### ISSUE TITLE
Bug: Following development instructions to the letter does not work

### ISSUE THREAD

**Issue by vegabook** [bonfire-networks/bonfire-app#469]
Following exactly what is said in the [developer instructions](https://doc.bonfirenetworks.org/hacking.html), gives these errors:

![image](https://user-images.githubusercontent.com/3780883/215288533-2d1b85c8-11c6-4ff1-aba2-a29914205a94.png)

Trying to run non-docker ie, [Option D](https://doc.bonfirenetworks.org/hacking.html#option-d-the-bare-metal-if-you-don-t-use-docker), but it doesn't even let me get past the `just config` part.

All dependencies listed are installed, including yarn. It says something about `docker-compose` but why would I need this if I don't want to use docker and I'm (ahem) "just" trying to config?

```
🐘 tbrowne@logic:~/bonfire$ cat .tool-versions
erlang 25.2
elixir 1.14.3-otp-25
just 1.13.0
```

```
🐘 tbrowne@logic:~/bonfire$ uname -r
5.15.0-58-generic
🐘 tbrowne@logic:~/bonfire$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by mayel** [comment]
Hi @vegabook, did you also `export WITH_DOCKER=no` ?

**Comment by vegabook** [comment]
> Hi @vegabook, did you also `export WITH_DOCKER=no` ?

No I did not, @mayel , but I have now and it makes no difference:

![image](https://user-images.githubusercontent.com/3780883/215289594-c6c9aaf6-db5d-485f-830b-76c79191010d.png)

Also, the docs say you should do `just config` before doing option choice, which is why I didn't do it.

**Comment by mayel** [comment]
Definitely need to update the order of commands in docs. Seems you're getting a different error now though...

**Comment by mayel** [comment]
@vegabook there's was a missing `echo` in the justfile 🤦‍♂️ Can you please pull and try again?

**Comment by vegabook** [comment]
> @vegabook there's was a missing `echo` in the justfile man_facepalming Can you please pull and try again?

Sure @mayel 
```
🔥tbrowne@prime-ghost:~/bonfire$ just config
error: Expected '}', '(', '+', or '/', but found string
    |
585 |     {{ if WITH_DOCKER != "no" { "docker-compose up -d db search || echo \"WARNING: You may want to make sure the docker daemon is started or run 'colima start' first.\"" } else {echo "Skipping docker services"} }}
    |                                                                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mayel** [comment]
Oh yeah just is weird with quotes. One more time? 🤞

**Comment by vegabook** [comment]
Just for others who might see this. Please note that the `bonfire-app` has its own `.tool-versions` file in the repo itself, which will override the one in your home directory. So you should install the erlang and elixir versions, using [asdf](https://github.com/asdf-vm/asdf), that are specified in bonfire's .tool-versions to make things work.
