### ISSUE TITLE
Group mockups and main requirements

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#470]
After some brainstorming these are the mockups for the first implementation of groups. The main goal is to merge together chat and social network UX, in particular offering immediacy without simplifying too much. Let the user navigate between incremental degrees of complexities / customization.

We mostly used reddit, discord and element as references for designing bonfire groups, but some thoughts and features are specific for the fediverse. Among others, these are few requirements that will shape groups development in bonfire:

- A group can optionally be followed but to post or interact in it you must be a member
- A group being @ mentioned on the fediverse just tags it (like when you mention a user), to post in a group you have to specifically select it as context (see mockups below)
- A group has different moderation settings such as:  
  - Define activities as public or private for members 
  - Anyone can follow or join, or must request first, or invite-only? (all powered by boundaries but with nice presets and UX)
  - Group boundaries are applied to a post/object in it (and to comments on those), with option to lock it down further, but not to open it more
  - Flagging something/someone in a group is addressed first to group mods
  - group mods can delete activities 
  - Mods can post in the name of the group or using their regular user

### 1# mockup: General group view 

User joined groups live on the left sidebar (as in discord, element), where the first item (the home icon) represents the classic social network (with  local / remote / subscribed timelines)
A group can have its own visibility (public / private) and set of rules / CoC.
From within a group, the user has access to specific group timelines, and a list of topics that belong to the group itself.
Topics behaves like rooms (in discords) and can have their own specific boundaries / permissions 
Some of them can be read-only (like an announcements room) others more partecipative.
Anyone with the right permissions can create / join topics.

![MacBook Air - 1 (2)](https://user-images.githubusercontent.com/1852065/217307056-e266afd0-b2be-4ca0-b1ff-88dd65dd31d6.png)

### 2# mockup: group dropdown
Next the group name there's a dropdown to quick access the most relevant sections in groups (some items may be missing ?) w/ a focus on mods actions

<img width="313" alt="Screenshot 2023-02-07 at 17 39 00" src="https://user-images.githubusercontent.com/1852065/217307118-1c989955-6684-4d85-846c-bdf365df3208.png">

### 3# mockup: Pinned activities
Announcements, rules, changes - anything relevant will stay fixed on top of the group feed

<img width="796" alt="Screenshot 2023-02-07 at 18 24 08" src="https://user-images.githubusercontent.com/1852065/217318642-bef3d4ca-5ebf-4c2e-ac1d-a061be956116.png">

### 4# mockup: Group widgets
Groups will likely requires different widgets to show on the right sidebar, some of them includes the about widgets (that shows group description, members widgets)

<img width="248" alt="Screenshot 2023-02-07 at 17 39 38" src="https://user-images.githubusercontent.com/1852065/217307270-d53c8590-9ac6-4ec6-a1aa-6bded59884a4.png">

**Comment by mayel** [comment]
Glad to finally be working on this after so long thinking/talking about it!

**Comment by dajbelshaw** [comment]
Love this @ivanminutillo and echo @mayel that I'm glad you're working on this! Have you thought about how this would look on mobile? I don't know if you've got any figures for the split between mobile and desktop for Fediverse apps, but my assumption is that it would be heavily skewed towards mobile? 😄

**Comment by ivanminutillo** [comment]
Thanks for the prompt @dajbelshaw 
here a couple of mockups showing groups on mobile, the design pattern we followed is basically the discord one, which works pretty well. let me know what do you think :)

### Group view on mobile
![group view](https://user-images.githubusercontent.com/1852065/219958157-a30a2040-ff5f-4914-b479-7ea1fe9796b4.png)

### Group view on mobile - sidebar open
![group sidebar open](https://user-images.githubusercontent.com/1852065/219958156-cf654442-ef88-4ac4-9f82-87698ab58733.png)

**Comment by ivanminutillo** [comment]
There may be several layers of confusions between groups, topics (and spaces - when we'll include them).
To try avoiding it, we were discussing a couple of alternatives to create a clear division among them in the bonfire user experience.
The main objective is to avoid duplication of functionalities for each feature (spaces | groups | topics) and define clear purposes for each of them .  
A Space is the higher level, it can contain both groups and topics (An organisation can be a space, like bonfire itself, or any community, project, etc) 
A group can contain multiple topics. A group deals mostly with membership & access control - it defines who and how someone can join, list all participants, set/edit roles and moderation.
But all the activities happen within topics.
A topic inherit the access control from its parent group (or a space), but it can set custom access control (eg. the Announcement topic is more likely to be read-only, or other topics can have specific boundaries so that only specific users can add activities to it.

Below some mockups to try to better visualize the whole UX  

### A Space (or a community, we're still discussing the naming) called "Ceres rules the system" with its own set of groups (Welcome, Team, Contributors, Community) who themselves includes specific topics (rules, announcements, welcome, ...)
![MacBook Air - 6](https://user-images.githubusercontent.com/1852065/220139251-1d94d047-3fef-449c-908c-55e82f353b0e.png)

### The instance can be considered a "custom" space, where caretakers can create groups and topics, but it will include a custom navbar at the top
![MacBook Air - 7](https://user-images.githubusercontent.com/1852065/220140039-5816dd22-61f8-4b14-ba7a-cbb7fff85f0b.png)

Some more questions to ponder, if I join a group that does not belong to any space where / how can i access it?
- in the mockup above, I've imagined that the user would access all groups joined (both local and federated) that are not in any spaces from the left sidebar, while navigating the instance space. Maybe we need to add the possibility to star a group to make it show on the instance sidebar ?

**Comment by mayel** [comment]
Summarising a few points we've been discussing based on those mockups:
- until a "spaces" feature is introduced (out of scope for now), groups and topics would be shown in default user (all groups I join and topics I follow) and instance spaces
- groups could be just about membership control, where discussions and activities happen within topics, so a group is a container for members and topics (you can't post in it directly) 
- joining a group could [automatically or as suggestion?] mean also following a default topic (eg. 'general' or 'welcome' or 'announcements')
- looking at a space/community shows me the publicly-visible groups and topics within it, and then I can join (or request to join) the groups I want (but need to get added to invite only ones), and follow the public topics I am interested in
- groups can have visibility/membership options such as:
  -     public group, anyone can join
  -     public group, people can request to join
  -     public group, invite only
  -     private group, people can request to join
  -     private group, invite only
- topics can have boundaries like:
  -    announcement topic, only some can post
  -    curated, you can post (tag it) and it has to be approved by a mod
  -    open, all members of parent group (or anyone if not part of a group) can post

**Comment by tallship** [comment]
This is looking exceptionally well!

**Comment by ivanminutillo** [comment]
As spaces will not be part of the first set of releases, here a mockup of groups and topics on the instance level

![MacBook Air - 8](https://user-images.githubusercontent.com/1852065/220280998-94ed4ac8-f2fe-4347-8351-984970cfd76a.png)

**Comment by codegod100** [comment]
I'm so excited for this

**Comment by tallship** [comment]
I'm not grasping the **"Spaces"** concept.

The website acknowledges that we're using the usual nomenclature of **"Instances"** to refer as a Bonfire server installed and deployed into production, like most other Fediverse platforms do.

Some however, do not. i.e., *Hubzilla*, for example, calls them **"Hubs"**, while *Diaspora* calls them **"Pods"**, Etc.

You offered the following as an explanation:

> A Space is the highest level, which can include both groups and topics. An organization, community, or project, like Bonfire, can be a space.

So, how is (or would/might) a **"Space"** differ from an **"Instance"**?

The only thing really, that for me, comes to mind would be if a single instance of *Bonfire* were a***multi-tenant*** installation supporting VirtualHosts like **Takahē** does in conjunction with Apache or Nginx. But then, fur so intents and purposes, those VirtualHosts would just still be instances in their own right.

⛵

.

**Comment by mayel** [comment]
We get the name "spaces" (and some of the inspiration for the feature) from Element, the official Matrix chat client, which you can read about here:
https://element.io/blog/spaces-the-next-frontier/
https://element.io/blog/spaces-blast-out-of-beta/

To avoid confusion, spaces would be quite different from instances because they'd be federated, meaning you could participate in a space from an instance other than your own, and a space could contain/include groups/topics/users/posts/etc from across the fediverse.

**Comment by tallship** [comment]
Instead of recreating the wheel from scratch, I'd like to offer for the discussion a bit about functional criteria for federating groups that I enumerated [elsewhere here](https://gitlab.com/soapbox-pub/soapbox/-/issues/1347).

Also, I'll note that I'm extremely excited and optimistic about the federating groups feature set, as it is so far presented here wrt Bonfire (the wireframing mockups are quite awesome, IMNSHO).

It would be a great thing to roll these out even in beta as only the second Fediverse server platform to offer federating groups - *Calckey*, insofar as I know, is the only Fediverse platform to have fully deployed operational federating groups on production instances in the Fediverse to date, although there is *guppe groups* (but that construct is nothing more than the analog of a Majordomo or ezmlm listserv).

*Soapbox* has federating **events**, and also works seamlessly with *Mobilizon* servers, but those aren't groups by any measure, and really, it's mute like the FOSS based equivalent of "Meetup .com" in the Fediverse.

Bonfire has a window to steal the show and spotlight here 👍

**Comment by ivanminutillo** [comment]
Group page mockup

![MacBook Air - 13](https://user-images.githubusercontent.com/1852065/221836387-3f0498ba-feb5-404d-b29c-4dadab66320f.png)

**Comment by ivanminutillo** [comment]
**Create a group (form)**
- name, description, bg image
- Make it publicly discoverable
- Open | Request to join | Invite only

**Group Settings**
- Edit name, description, images
- Edit discoverability
- Edit joining setting
- Create invite link
- Members list (+ remove users)
- Roles (starting simple: make a member a co-caretaker)
- Moderation (deal with flags, blocks)
- Notification (join requests, flags)

**Create topic (form)**
- name, icon
- who can post: Announcement (mods | Group-members only
- can others make submissions?
- can non-mods view submissions?

**Topic settings**
- Edit name, icon
- Edit type
- Submissions (+ option to publish them if mod)

**Comment by loid345** [comment]
I think it's necessary to add group url change setting to initial functions
