### ISSUE TITLE
instance members view

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#489]
Current:
![image](https://user-images.githubusercontent.com/1852065/223099957-2d9e3d14-8c4d-4c47-802b-e1de3ff84a16.png)

Issues / to be improved: 
- [x] Blocked users do not appear in the list
- [x] add more actions: Add a role to a user 
- [x] Show if any user has already been blocked 
- [x] Prob having "block" as main action does not feel just right, it's quite aggressive

**Comment by mayel** [comment]
seems to work:
<img width="606" alt="Screenshot 2023-08-27 at 13 52 06" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/5574bb3a-fcbd-45b0-966c-92e8742e2002">
