### ISSUE TITLE
post with custom boundaries should appear in "my feed" for users who can see it

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#498]

**Comment by ivanminutillo** [comment]
relevant test https://github.com/bonfire-networks/bonfire_ui_social/blob/main/test/views/boundaries/boundaries_in_feeds_test.exs#L68

**Comment by mayel** [comment]
all tests in https://github.com/bonfire-networks/bonfire_ui_social/blob/main/test/views/boundaries now passing :)
