### ISSUE TITLE
Apparently I can add multiple times the same remote actor to the composer boundary

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#520]

**Comment by mayel** [comment]
seems I remote users often don't even appear in boundary dropdown as they may not have been indexed in Meili

**Comment by mayel** [comment]
can't seem to add a user multiple times though

**Comment by mayel** [comment]
still relevant?

**Comment by ivanminutillo** [comment]
lets close it for now then
