### ISSUE TITLE
I can't ghost a user from the ghosted view

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#522]
"The function do_handle_event/3 in module Elixir.Bonfire.Boundaries.Web.CircleLive didn't receive data in a format it can recognise: \n\"** (FunctionClauseError) no function clause matching in Bonfire.Boundaries.Web.CircleLive.do_handle_event/3\"\n```\n    (bonfire_boundaries 0.1.0) lib/web/components/circles/circle_live.ex:118: Bonfire.Boundaries.Web.CircleLive.do_handle_event(\"add\", %{\"subject\" => \"01GMDXNQ8YDNGTBZBVBSRQA631\", \"value\" => \"\"}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{no_live_event_handler: true}, __context__: %{csrf_token: \"0BRfUPxLvPR0kPyEe7MOQ-2H\", current_account: %Bonfire.Data.Identity.Account{__meta__: #Ecto.Schema.Metadata<:loaded, \"bonfire_data_identity_account\">, accounted: #Ecto.Association.NotLoaded<association :accounted is not loaded>, auth_second_factor: #Ecto.Association.NotLoaded<association :auth_second_factor is not loaded>, credential: #Ecto.Association.NotLoaded<association :credential is not loaded>, email: #Ecto.Association.NotLoaded<association :email is not loaded>, id: \"01GMDXMBWT44MSGF9WGQARVAWB\", settings: nil, shared_users: #Ecto.Association.NotLoaded<association :shared_users is not loaded>, users: #Ecto.Association.NotLoaded<association :users is not loaded>}, current_account_id: \"01GMDXMBWT44MSGF9WGQARVAWB\", current_app: :bonfire_boundaries, current_extension: %{app: :bonfire_boundaries, exclude_from_nav: true, href: \"/boundaries\", icon: \"twemoji:handshake\", module: Bonfire.Boundaries.Web.BoundariesLive, name: \"Boundaries\", type: :link}, current_params: %{\"tab\" => \"ghosted\"}, current_url: \"/boundaries/ghosted\", current_user: %Bonfire.Data.Identity.User{__meta__: #Ecto.Schema.Metadata<:loaded, \"bonfire_data_identity_user\">, accounted: %Bonfire.Data.Identity.Accounted{__meta__: #Ecto.Schema.Metadata<:loaded, \"bonfire_data_identity_accounted\">, account: #Ecto.Association.NotLoaded<association :account is not loaded>, account_id: \"01GMDXMBWT44MSGF9WGQARVAWB\", id: \"01GMMQKFJ688WWM18C1TTKSFQ9\", pointer: #Ecto.Association.NotLoaded<association :pointer is not loaded>, user: #Ecto.Association.NotLoaded<association :user is not loaded>}, actor: #Ecto.Association.NotLoaded<association :actor is not loaded>, boost_activities: #Ecto.Association.NotLoaded<association :bo\n```",

**Comment by mayel** [comment]
selecting a user shows this which disappears when reloading
<img width="605" alt="Screenshot 2023-04-16 at 12 44 02" src="https://user-images.githubusercontent.com/115318/232260218-cbe79a8f-3c34-48cf-bca4-61c28e75c774.png">

**Comment by mayel** [comment]
seems like it does add it but doesn't show the list

**Comment by mayel** [comment]
fixed
