### ISSUE TITLE
make sure previewContent appears instantly

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#530]

**Comment by mayel** [comment]
there's already a loader for the comments:
<img width="666" alt="Screenshot 2023-04-16 at 12 10 17" src="https://user-images.githubusercontent.com/115318/232259352-42df8bef-1d0e-4189-a3b6-fd30f68a1aa1.png">

**Comment by mayel** [comment]
Is this issue still relevant?

**Comment by mayel** [comment]
yeah would be good to find out when that happens and fix it instead
