### ISSUE TITLE
Add a placeholder for uploaded images and subject minimal when the feed is loading

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#532]

**Comment by mayel** [comment]
We can't do this without preloading the data from DB (i.e. checking the activities is replying to something or has attached media) which would defeat the purpose of async preloading. So it's a decision between UX and performance here I'm afraid.

**Comment by mayel** [comment]
I guess what we could do is use some caching, not of the actual data but just of booleans or number of attachments.

**Comment by ivanminutillo** [comment]
can we just preload the minimum amount of data to know in advance if there is an attached media or reply_to, and if so we show an indicator while async preloading it? Layout shifts are not that good from a a11y pov
