### ISSUE TITLE
test: request and accept/reject of follows

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#537]

**Comment by ivanminutillo** [comment]
the follow_request_dance_test is failing because the "request_before_follow" param is not correctly assigned when the fake_user is generated via opts (that is the same issue i got while doing manual testing)

**Comment by mayel** [comment]
so it does look like request_before_follow is taken into account and applying the :no_follow ACL but then check_follow isn't returning :not_permitted like it used to...
