### ISSUE TITLE
Add negative roles and include them in the composer select

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#547]
- [x] add negative roles 
- [x] include negative roles in composer & boundary dropdowns
- [x] show previously-selected negative roles in boundary dropdown
- [x] write tests to check that negative roles are correctly applied

**Comment by mayel** [comment]
roles as they are implemented now are just lists of verbs in config, which positive permission is granted to, so we can have a reverse version of those:
- can't read
- can't interact
- can’t participate
- etc

our current roles are hierarchical, eg:
- read: see, read
- interact: see, read, boost, like
- participate, see, read, boost, like, reply

so the negative ones would have to apply negative permissions in an inverse hierarchy:
- can’t read: see, read, boost, like, reply, delete, etc, etc
- can’t interact: boost, like, reply, delete, etc, etc
- can’t participate: reply, delete, etc, etc

**Comment by mayel** [comment]
<img width="1171" alt="Screenshot 2023-04-17 at 19 55 01" src="https://user-images.githubusercontent.com/115318/232422458-405fe96b-159c-44b5-9886-2f9aef25d278.png">

**Comment by ivanminutillo** [comment]
added tests for negative roles and spotted a bug with cannot interact role (like is disabled as expected but boost action remained enabled)  all the rest passed, great work :+1: 

https://github.com/bonfire-networks/bonfire_ui_social/blob/main/test/views/boundaries/negative_boundaries_test.exs#L58

For the sake of simplicity, I would leave only cannot administer and remove cannot contribute, given that atm the only action they can perform with that role assigned is deleting the post

**Comment by mayel** [comment]
hmm, I noticed in the UI as well when boundaries are still not loaded that boost is already enabled, but I can't spot a difference between the logic in `BoostActionLive` and `LikeActionLive`...

**Comment by mayel** [comment]
ah found it!
