### ISSUE TITLE
when changing a negative permissions role, make sure it replaces all permissions rather than just adding

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#549]
eg. when you change from "Cannot administer" to "Cannot read", it doesn't seem to change anything

**Comment by mayel** [comment]
seems this doesn't happen in the backend, may need a UI test to catch it: https://github.com/bonfire-networks/bonfire_boundaries/blob/main/test/acls/acls_test.exs#L157

**Comment by mayel** [comment]
@ivanminutillo says:

> i discovered something more on the downgrade role bug 
> if you add a new user to a boundary, and select "cannot read" from the select, then refresh the page, it will show "cannot administer"
> the issue seems only with cannot_read that somehow defaults to cannot administer
> all the other options seems to work fine
> i've cloned that test changing from cannot_read and cannot_administer to cannot_interact and cannot_participate and it passes

**Comment by mayel** [comment]
@ivanminutillo thanks for that, it helped pinpoint the issue to how the role name was looked up (based on a list of verbs), thankfully it was not a logic bug in boundaries 😅

**Comment by ivanminutillo** [comment]
this WIP introduced a bug when adding a new circle/user to a boundary - here the stacktrace:
```
[debug] SQL query: ok db=0ms source="bonfire_data_access_control_grant"
  DELETE FROM "bonfire_data_access_control_grant" AS b0 WHERE ((b0."subject_id" = '01GZEDK5CT22AWVWVJ3DXS1C3G') AND b0."acl_id" = ANY('{01GZEDJH5SZXPVVPRVVXJQ35Y9}')) 
    (bonfire_boundaries 0.1.0) lib/contexts/grants.ex:144: Bonfire.Boundaries.Grants.grant_role/4
    (elixir 1.14.4) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (stdlib 4.3.1) maps.erl:411: :maps.fold_1/3
    (elixir 1.14.4) lib/enum.ex:2480: Enum.map/2

```

apparently the grant_role fn, line 144: `remove_subject_from_acl(subject_id, acl_id)`
