### ISSUE TITLE
Bug: I can see other user flags on local feed --> with flags specific actions (even if Im not an admin)

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#553]
- login as ivan -> flag a post
- login as carl -> navigate to local timeline 
![Schermata del 2023-04-28 11-43-48](https://user-images.githubusercontent.com/1852065/235114378-9f42d887-2c4e-4db0-9acd-276209af1dd9.png)

**Comment by mayel** [comment]
tests seem to say it's fixed, let's double check in the UI

**Comment by ivanminutillo** [comment]
nope, not sure why but the test passes but in the UI you'll keep see the flags in the local feed
