### ISSUE TITLE
As an admin I may find useful to have a "flags" tab in activities

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#554]
From
![Schermata del 2023-04-28 11-46-06](https://user-images.githubusercontent.com/1852065/235115054-b3993c5d-c14d-4f8d-b0ec-b2dd9d341bf7.png)

to
![Schermata del 2023-04-28 11-47-36](https://user-images.githubusercontent.com/1852065/235115178-d553f7f2-a20d-42e4-995e-ab2c463aca87.png)

**Comment by mayel** [comment]
done

**Comment by ivanminutillo** [comment]
seems though the flags listed in the flags feed are only the ones created by the current_user, not from all the instance users
