### ISSUE TITLE
Bug: If I already flagged a post, I want to have a label saying "Already flagged" replacing the flag button 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#557]

**Comment by mayel** [comment]
The issue with this is that it's one more thing to preload for every item in the feed. May I suggest instead that when you click "Flag" it checks at that point and instead of the modal asking for confirmation you get a message that you've already flagged it?

**Comment by mayel** [comment]
implemented this approach for now

**Comment by ivanminutillo** [comment]
:1st_place_medal: wonderful
