### ISSUE TITLE
Block tests & Livehandlers

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#561]
https://github.com/bonfire-networks/bonfire_ui_social/blob/main/test/views/moderation/block_test.exs
- [x] Ghosting a user works
- [x] Silencing a user works
- [x] I can see a list of ghosted users
- [x] I can see a list of silenced users
- [x] I can unghost a previously ghosted user
- [x] I can unsilence a previously silenced user
- [x] I can see if I silenced a user from their profile page
- [x] I can see if I ghosted a user from their profile page
- [x] if I silenced a user i will not receive any update from it
  - [x] i'll not see anything they publish in feeds
  - [x] i'll be able to view their profile or read post via direct link
  - [x] i'll not see any @ mentions or DMs from them
  - [x] I'll not be able to follow them
  - [x] if I unsilence them i'll not be able to see previously missed updates
- [x] if I ghosted a user they will not be able to interact with me or with my content
  - [x]  Nothing I post privately will be shown to them from now on
  - [x] They will still be able to see things I post publicly.
  - [x] I won't be able to @ mention or message them.
  - [x] they won't be able to follow me
  - [x] You will be able to undo this later but they may not be able to see any activities they missed.
- [x] As an admin I can see a list of instance-wide ghosted users
- [x] As an admin I can see a list of instance-wide silenced users
- [x] As an admin I can unghost a previously ghosted user instance-wide
- [x] As an admin I can unsilence a previously silenced user instance-wide

**Comment by ivanminutillo** [comment]
Current broken tests:
- [ ] I can see if I silenced a user from their profile page (The implementation is missing)
- [ ] I can see if I ghosted a user from their profile page (The implementation is missing)
- [ ] As an admin I can ghost a user instance-wide (instance-wide ghost does not seem to have effects on other users)
- [ ] As an admin I can silence a user instance-wide (instance-wide silence does not seem to have effects on other users)

**Comment by mayel** [comment]
some of those are in the feeds milestone: #195 #199
