### ISSUE TITLE
Bug: Dev introduction instructions don't work, don't document PUBLIC_PORT

### ISSUE THREAD

**Issue by makoConstruct** [bonfire-networks/bonfire-app#580]
**Describe the bug**
Following instructions in https://bonfirenetworks.org/docs/hacking/ , after running `just config`,
```
error: Call to function `env_var` failed: environment variable `PUBLIC_PORT` not present
   |
45 | PROXY_CADDYFILE_PATH := if env_var('PUBLIC_PORT') == "443" { "./config/deploy/Caddyfile2-https" } else { "./config/deploy/Caddyfile2" }  
   |                            ^^^^^^^
```

I then set PUBLIC_PORT to 4000 and tried again, and it still didn't work

```
> just config
Switching to flavour 'classic'...
Using flavour 'classic' at flavours/classic with env 'dev' with vars from ./flavours/classic/config/dev/.env 
rm: cannot remove '.env': No such file or directory
just build
Using dev env, with flavour: classic at path: flavours/classic
dev-services: line 1: docker: command not found
WARNING: You may want to make sure the docker daemon is started or run 'colima start' first.
Light that fire! bonfire with classic flavour in dev - docker:total - 0.9.2-beta.5 - a318d2273c - flavours/classic - unix/linux on x86_64
mkdir -p deps
docker compose pull
build: line 1: docker: command not found
error: Recipe `build` failed on line 658 with exit code 127
error: Recipe `setup-dev` failed on line 110 with exit code 127
error: Recipe `flavour` failed on line 91 with exit code 127
error: Recipe `config` failed on line 85 with exit code 127
```

**Bonfire environment (please complete the following information):**
- flavor: classic (btw, it would be nice to have a more complete explanation of the flavors, but not important if we're just focusing on classic)
- version: 0.9.2-beta.5 (found in `mix.exs`)
- Running with Docker? (see WITH_DOCKER env variable): uh the variable's empty
- Running env: dev?

**Device (please complete the following information):**
 - Device: desktop
 - OS: nixos

**Comment by Greenheart** [comment]
I got the same error while setting up the dev environment. I'm investigating possible solutions and will report back here if i find anything! :)
