### ISSUE TITLE
Organize instance circles in categories and add pagination

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#581]
Instance circles in production may grow exponentially in relatively short amount of time, since a new circle is created for every instance a local user had contact with.
To navigate instance circles I propose to add tabs on top of the view and divide circles in:
- Custom (may find a better name for the ones created by instance caretakers)
- Instances
- Default 

And add pagination for those lists who surpass 10-15 items

**Comment by mayel** [comment]
On what view is that? I recently changed instance circles to belong to the AP circle rather than the admins one to avoid them getting mixed in.

**Comment by ivanminutillo** [comment]
instance settings -> instance circles (view it on campground)

**Comment by mayel** [comment]
And a checkmark when creating an instance boundary whether it should be shown to all users (including in composer) or only used by admins.

**Comment by ivanminutillo** [comment]
is it really worth to differentiate the first 2? any use case you already have in mind that prevent to have them combined in the same tab?

**Comment by mayel** [comment]
For clarity. One category to be used only by admins eg. when setting boundaries for moderators and other roles on the instance. The other to create similar things to the current defaults like Public/Local/Etc
