### ISSUE TITLE
Research, test and choose an open-source search backend (BON-75)

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#59]
MeiliSearch seems the way to go so far. Open to exploring alternatives...

---
via https://github.com/bonfire-ecosystem/bonfire-app/issues/59

**Comment by volanar** [comment]
https://manticoresearch.com/
https://github.com/manticoresoftware/manticoresearch-elixir

**Comment by mayel** [comment]
Thanks @volanar, we'll look into those. Any chance you know of any pros/cons compared to Meili?

**Comment by volanar** [comment]
> Спасибо @volanar , мы их рассмотрим. Есть ли шанс, что вы знаете какие-либо плюсы / минусы по сравнению с Мейли?

Manticore is a great fork of sphinx search, written in C++, faster and more stable than MeiliSearch, and designed for big data
