### ISSUE TITLE
if I am replying to a group discussion, the composer must inherit the group boundary

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#600]

**Comment by mayel** [comment]
Already the case, see for example when replying to a post in a private group, the reply automatically is set to custom boundaries with the following:
<img width="596" alt="Screenshot 2023-06-12 at 10 52 01" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/d84cb9cc-619d-406b-8f99-12b137020c98">

**Comment by mayel** [comment]
created #602 for that
