### ISSUE TITLE
Bug: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by hl0dwig** [bonfire-networks/bonfire-app#608]
**Describe the bug**
I'm trying to install the docker version on Ubuntu Server 22.04.2
I'm stuck at the step "sudo just rel-run" with a red error message _"failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres""_

**To Reproduce**
1. Follow the guide to install the docker version "option B"
2. Set any value for the variable POSTGRES_PASSWORD in the .env file
3. Launch the command "just rel-run"

**Expected behavior**
The server should be running :p

**Bonfire environment (please complete the following information):**
- Running with Docker? (see WITH_DOCKER env variable):  none
- Running env: prod with docker image
- Running version (check on your instance's homepage): bonfire-0.1.0-beta.3
- Running flavour: classic
- Running any extra/forked extensions: no

**Comment by mayel** [comment]
Hi @hl0dwig, thanks for giving it a go :) 

When you say "set any value for the variable POSTGRES_PASSWORD", did you change that value at some point during the install? In which case it's possible the postgres container was set up with the initial password and now the app is trying to connect with the new one.

**Comment by hl0dwig** [comment]
I've tried to comment the line, just to see the behavior and of course I've got another error:

```
ERROR! Config provider Config.Reader failed with:
** (RuntimeError) Environment variables for database are missing.
For example: DATABASE_URL=ecto://USER:PASS@HOST/DATABASE
You can also set POSTGRES_PASSWORD (required),
and POSTGRES_USER (default: postgres) and POSTGRES_HOST (default: localhost)
```

**Comment by mayel** [comment]
@hl0dwig I've had the same issue before and starting from scratch is easier said than done because of various docker caching mechanisms. Wish I remembered the incantations that got me out of it...

**Comment by mayel** [comment]
Another angle would be manually changing the password on the postgres container.

**Comment by hl0dwig** [comment]
Thanks for your help @mayel I think you were right at the beginning! I've deleted all the containers/volumes/images of docker, and restarted from a "true" scratch, now it's running!! (well, I ended up on the " Something went wrong " page but I'm making progress and this is out the context of this false bug :p)

**Comment by pnwmatt** [comment]
For future internet people looking at this thread, an easy way to do a clean reset is:

1. `just rel-stop`, `docker ps -a | grep bonfire`.  For each of these, `docker rm <hash>`.  Note: I needed to `docker stop bonfire_release-sonic-1` after `just rel-stop` to completely remove all the instances.
2. `docker volume ls | grep bonfire` and `docker volume rm <name>` each of these.

With all the persistent state removed, you can now recreate the containers with `just rel-run`.  This takes a few minutes to prepare everything and once it's working you'll see the elixir prompt `iex(bonfire@be66b92fdcea)1>`

It's likely that you can get away with only removing the postgres volume (which requires rm'ing the container), however I just went ahead and did a clean wipe of all containers and volumes to resolve this issue and successfully create my initial account.
