### ISSUE TITLE
Include toggles in threads & user preferences for different modes & sort orders

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#609]
- [x] **Layout**
- [x] Standard
- [x] [Compact](https://github.com/bonfire-networks/bonfire-app/issues/623) 
- [x] Flat
---
- [x] **Order by**
- [x] Chronological
- [x] By latest reply (so an older branch gets resurfaced if someone replied to it)
- [x] By amount of replies
- [x] By boosts
- [x] By likes
---
- [x]  **Sort order**
- [x] Newest (or most) first
- [x] Oldest (or least) first

**Comment by mayel** [comment]
we could #590 for flat threads to begin with
