### ISSUE TITLE
Create activity preview UI components for unimplemented object types (eg Video, Event,...) 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#620]
We support including them in feeds using the APActivity json object (https://github.com/bonfire-networks/bonfire-app/issues/44), but need nice ways to view them 

- [x] pictures (eg pixelfed)
- [x] video (eg. peertube)
- [x] events (eg. mobilizon, https://gancio.org -> need a sample JSON from the latter)
- [x] audio / podcasts (eg. castopod)
- [x] longform posts (eg. writefreely/writeas)
- [x] books (eg [bookwormhole](https://books.theunseen.city/book/2192/s/1984-george-orwell))
- [x] live streaming media (eg. Owncast and https://codeberg.org/namekuji/audon/wiki/Home)

**Comment by mayel** [comment]
Added `ActivityPub.Fixtures.insert_all` as a way to populate the dev DB with a bunch of example AP data

**Comment by loid345** [comment]
Don't forget about discourse
https://meta.discourse.org/t/activitypub-plugin/266794/67
