### ISSUE TITLE
implement ability to edit an existing object's boundaries

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#630]
- [x] edit custom ACL (eg. on mention-only post)
- [x] remove presets
- [x] add presets 
- [x] add a custom ACL if the object doesn't have one

<img width="559" alt="Screenshot 2023-10-28 at 12 44 51" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/e6f2799b-07cd-4888-8dd1-6468b43cb4d8">

currently there's 4 sections:
- your computed role
- custom permissions on that object (eg. if you did mentions-only) with the ability to edit or add more
- presets that were selected (either built-in ones or your own boundary presets) with the ability to remove
- users/circles in the presets from previous section with their computed roles (read only)

**Comment by ivanminutillo** [comment]
can it be further simplified like this:
![image](https://github.com/bonfire-networks/bonfire-app/assets/1852065/243b2988-4fb2-47bb-9b34-c2c73ad3980b)
basically composed of:
- preset boundary (if any)
- custom / ad-hoc acls

**Comment by mayel** [comment]
would require lots of re-implementation, for a result which would be limited and not be able to handle all scenarios

**Comment by mayel** [comment]
I think we could simplify by separating out 'view boundaries' and 'edit'

**Comment by mayel** [comment]
> I think we could simplify by separating out 'view boundaries' and 'edit'

done
