### ISSUE TITLE
better handling of video uploads

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#655]
Currently it's possible to upload videos in bonfire, but the upload in composer does not show them properly. 
The activity preview treats the uploaded video same way as an external link.

**Comment by ivanminutillo** [comment]
- [ ] Separate video uploads from images
- [ ] Add a custom modal to show video
- [ ] Add sticky modal to show inline videos while browsing

**Comment by ivanminutillo** [comment]
IMO we should not open the video in a modal because most of the time I'd like to eg. read comments while see the video and rarely i want to switch to full video - wonder if we can have an alternative modal for media that keep load the video keeping the position or something similar

**Comment by mayel** [comment]
we do have an alternative modal, it gets pinned to bottom left of screen at the moment, does need more styling though
