### ISSUE TITLE
Add sensitive content checkbox when adding media to composer

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#656]
Shall we also add a preference to automatically make all the media sensitive in the user feed?

**Comment by mayel** [comment]
I think CW with a label is preferable because it give you a hint to decide whether you want to reveal the contents. A checkbox would anyway have to add a label for interop reasons (eg. "Sensitive Content")

**Comment by ivanminutillo** [comment]
that's completed!
