### ISSUE TITLE
submitting a post from compose with a body and an image results in only the image being sent to back-end

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#663]

**Comment by ivanminutillo** [comment]
ha! this only happens when you add the media after adding the post content, if you first add the media and then write something the post is published correctly, this means the media somehow reset the body content

**Comment by ivanminutillo** [comment]
mmm not always the same result. But when instead I add a media, then remove it, the body content shows up correctly

**Comment by ivanminutillo** [comment]
fixed
