### ISSUE TITLE
test/fix HTTP Signatures implementation 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#666]
- [x] send signatures with fetches and POST
- verifying signatures we receive
	- [x] for POST
	- [ ] #784

**Comment by mayel** [comment]
all tests pass :)

**Comment by ivanminutillo** [comment]
where `fetch_public_key` and `refetch_public_key` (from ActivityPub.Safety.Signatures module ) are supposed to be called? 
can't find anywhere apart from signature_tests

**Comment by mayel** [comment]
notice the module doc says "Implementation for behaviour from `HTTPSignatures` library", meaning those functions are called by that lib: https://github.com/bonfire-networks/http_signatures

**Comment by mayel** [comment]
signature verifications now working
