### ISSUE TITLE
UI preview misskey/firefish pages 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#674]
example: https://misskey.io/@hakohako_f2/pages/mfm-cheat-sheet

**Comment by mayel** [comment]
`curl -L -H 'Accept: application/activity+json' -v http://misskey.io/@hakohako_f2/pages/mfm-cheat-sheet` seems to indicate that misskey pages don't federate (i.e. don't offer AS JSON)

**Comment by mayel** [comment]
same for firefix
