### ISSUE TITLE
explore supporting MFM

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#676]
http://misskey.io/notes/9ia8avub1a https://misskey.io/notes/9ca1vu48ui https://misskey.io/notes/9ie68eqhwy

**Comment by mayel** [comment]
we now parse and display MFM markup, still need #713 to be able to show MFM with images:
![Screenshot 2023-09-24 at 19 16 27](https://github.com/bonfire-networks/bonfire-app/assets/115318/5b35d7a7-7c91-46b1-b704-2b37e8025931)
