### ISSUE TITLE
Write tests to verify that settings are applied correctly

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#679]
### Appearance
- [x] Select theme
- [x] Font
- [x] Language
- [x] composer
- [x] Brand (Show only the logo or logo + instance name)
- [x] avatar shape
- [x] hide avatar
- [x] Animal avatars (Show randomly-generated animal avatars for users without a profile picture?)
- [x] prefer compact layouts
- [x] hide actions on feed
- [x] hide actions on discussions

### Behaviours
- [x] Feed activities (What activities to include in home feeds by default)
- [x] Default feed (Select the feed you want to display when visiting the activities and dashboard pages: my feed, local, remote)
- [ ] Feed default time limit (Select the time limit you want to use by default (can always change in the feed controls options)
- [ ] Feed default sorting (Select the default sorting options for your feeds (can always change in the feed controls options)
- [ ] How many items to show in feeds and other lists
- [x] Enable Infinite scrolling
- [ ] Sensitive media
- [ ] Hide media
- [x] discussions default layout
- [x] discussions default sort
- [x] Highlight Notifications indicators (Use the primary color to highlight the notifications indicator)
- [x] Show reaction counts (likes / boosts) (You will see the number of reactions to activities (may not indicate the real amount for federated posts)
### Privacy & Settings
- [ ] Discoverability (I  DO NOT want my profile (@username) and content to appear publicly in search engines (in Bonfire, the fediverse, and the web in general) #824 
- [x] Default boundaries (Specify your default boundary when publishing a new activity)

**Comment by ivanminutillo** [comment]
if discoverability is opted out, I expect to not see the user in the users directory list (that's how i'd frame the test for the sake of simplicity atm)

**Comment by ivanminutillo** [comment]
> Feed default time limit (Select the time limit you want to use by default (can always change in the feed controls options)

not sure how to test this one, except from testing a data-role on the feed wrapper - that shows the current time limit

**Comment by ivanminutillo** [comment]
> How many items to show in feeds and other lists
adding a test for it now, will fail because the :default_pagination_limit is always returned from Config, meaning it will only take in considearion the instance default value i guess

**Comment by mayel** [comment]
> Feed default time limit: not sure how to test this one, except from testing a data-role on the feed wrapper - that shows the current time limit

That prob wouldn't be useful since it would just output the setting, rather than if the setting is applied to the query. 

> How many items to show in feeds and other lists: the :default_pagination_limit is always returned from Config, meaning it will only take in considearion the instance default value i guess

Ah we should switch default_pagination_limit to use Settings rather than Config, as long as we have pagination_hard_max_limit for the admin to set a ceiling (since this affects resource use and performance).
