### ISSUE TITLE
posts on user profile do not show the subject

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#692]
https://campground.bonfire.cafe/@ivan/posts

**Comment by mayel** [comment]
that's on purpose, since it's repetitive

**Comment by mayel** [comment]
Oh "unsupported type or deleted object" is a new bug though

**Comment by ivanminutillo** [comment]
> that's on purpose, since it's repetitive

mmm I disagree with that, for a UI being predictive is a foundational aspect, changing the layout of an element based on circumstances needs to be done really carefully because the drawbacks are much more impactful than benefits (esp. in this case since the activity preview it's one of our core element).

**Comment by mayel** [comment]
well imo whether we use the activity component or a beskope one is an implementation detail, but functionaly that page is just a list of posts by a single author, not a feed but more like a blog:
<img width="739" alt="Screenshot 2023-08-28 at 20 49 53" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/28eed4cb-a467-4e24-b60e-6bcc9eea788f">

**Comment by ivanminutillo** [comment]
I agree, but those are always blog posts previews, with a specific set of metadata: title, text, image... (therefore predictive for users) - our posts will differ one another in which metadata they contain - they can be few words with a link, only a bunch of  images, or a long text hidden by a CW. Therefore the activity previews will not result standard like the lists you posted (eventually if the user marks the post as blog post we can show them in a list like that)

**Comment by ivanminutillo** [comment]
would actually be very nice to have the possibility to mark a post as an article, so that it is formatted in a different way and show in it's own list - this way users may have the standard activity feeds (with thoughts, media shared etc) and a blog section (and we can start publishing bonfire posts on the instance)
