### ISSUE TITLE
feed select (my feed, local, remote) not working on posts view (redirect to /activities)

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#693]
https://campground.bonfire.cafe/feed/filter/posts

**Comment by mayel** [comment]
yes it's only applied to dashboard

**Comment by ivanminutillo** [comment]
ah no! i'm talking about the select, clicking on "local" or "remote" etc redirects you to the activities feed ,even if I'm in the feed/filter/posts

**Comment by mayel** [comment]
should we hide the Posts link for now until we rethink it and/or add feed filters?

**Comment by ivanminutillo** [comment]
yes
