### ISSUE TITLE
Fix UI:Social broken tests

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#699]
140 tests, 57 failures, 7 excluded

- [ ] ui_social
- [ ] ui_social_graph
- [ ] ui_posts
- [ ] ui_messages
- [ ] ui_moderation

**Comment by ivanminutillo** [comment]
down to 18 failures :)

**Comment by ivanminutillo** [comment]
down to 6, almost all related to pagination

**Comment by ivanminutillo** [comment]
back to 37 :/

**Comment by mayel** [comment]
dup
