### ISSUE TITLE
Maximum file size of uploads attached to a post or other activity

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#738]

**Comment by ivanminutillo** [comment]
done!

**Comment by makoConstruct** [comment]
Would the misskey approach to managing user storage costs be a better solution to the underlying problem, here? On misskey, each user can upload a certain total quantity of files, and after that point they have to go through their drive and clear up space if they want to upload more. It prevents abuse without, like, making it impossible for an instance to host videos.

Implementation detail: I notice that the current system essentially gives each user as much storage as they have posts. If you're constraining posting rate, then that's a scheme where they get more storage over time. That actually makes a bit of sense (users storage needs increase as time goes on, and trust also increases over time), so you could replicate this with an option (on by default?) to give a user more storage the longer they've been on the instance.

**Comment by mayel** [comment]
@makoConstruct that's an interesting idea, thanks! another approach could also be #688
