### ISSUE TITLE
random fixes

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#763]
- [x] read actions in preview thread
- [ ] #793
- [x] mentions and follows show wrong icon when selected in composer
- [x] difficult to scroll nav on small screen
- [x] media in reply to not loading (maybe we don't want it to load? but it shouldn't show the skeleton in that case)
- [x] remove the check button on dm 
- [x] replying to a reply in a  flat (post or message) thread breaks reply_to UI
- [ ] #794

**Comment by ivanminutillo** [comment]
do not remember what "read actions in preview thread" means?

**Comment by mayel** [comment]
it should be "re-add"
