### ISSUE TITLE
Implement DB-based user/posts search

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#765]
- [x] user search
- [x] post search -> name/summary only
- [ ] make post/hashtag search the default and instead of 'all' have an 'other' tab? -> for now just did 2 tabs: everything and users
- [x] hashtag search -> need to first refactor to use Named mixin
- [x] search thread title and anything else with a name  
- [x] perform multi-type search in a single query
- [ ] #824
- [x] make meili optional in docker-compose
- [ ] #823

**Comment by ltning** [comment]
How is this supposed to work? Is it documented somewhere? I've got meilisearch running but I'd very much prefer not to need that in order to do "simple" searching on a relatively small base..
