### ISSUE TITLE
Auto-load older posts/ clicking on Next page does not seem to work

### ISSUE THREAD

**Issue by marek-lach** [bonfire-networks/bonfire-app#805]
I see on [the campground instance](https://campground.bonfire.cafe), that older posts are not automatically loaded on scroll (like on Mastodon, Pleroma etc.) that that there's a Next page button that needs to be clicked manually. Perhaps such a design-choice can save some server resources, but it seems clicking the button is not always responsive.

Reaching the end of one page could perhaps automatically load the next page instead (which would not be loaded if the bottom is not reached), so that the user can always reach older posts...

**Comment by mayel** [comment]
Hi @marek-lach and thanks for the report! Was that when logged in or just browsing as a visitor?
In any case we're currently addressing some bugs with pagination (#591 and #660), so hopefully it should be smoother in the next release.

 In terms of UX, there's these options in user settings (well-being section):
<img width="624" alt="Screenshot 2024-01-05 at 10 36 30" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/7ca2d4bf-5f0a-40df-a2c0-360c3c7d56aa">

**Comment by marek-lach** [comment]
> Hi @marek-lach and thanks for the report! Was that when logged in or just browsing as a visitor? In any case we're currently addressing some bugs with pagination (#591 and #660), so hopefully it should be smoother in the next release.
> 
> In terms of UX, there's these options in user settings (well-being section): <img alt="Screenshot 2024-01-05 at 10 36 30" width="624" src="https://private-user-images.githubusercontent.com/115318/294464959-7ca2d4bf-5f0a-40df-a2c0-360c3c7d56aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTM5NjQsIm5iZiI6MTcwNDQ5MzY2NCwicGF0aCI6Ii8xMTUzMTgvMjk0NDY0OTU5LTdjYTJkNGJmLTVmMGEtNDBkZi1hMmMwLTM2MGMzYzdkNTZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQyMjI3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWVhNTc1NWMzNThkY2JhMDgxNGMxN2YwMWNiOTZhMDkwNWYyZDYzMGM1MDNlMjliZGE3MDIyNTZiOGJkMGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7FugHH9l91OjC_Z1BYVlN3R1OsCSlx9-yZOrX7vsp2Q">

While browsing.
