### ISSUE TITLE
Bug: Unable to set up a dev environment

### ISSUE THREAD

**Issue by DnzzL** [bonfire-networks/bonfire-app#809]
**Describe the bug**
I cannot start a dev env from scratch.

**To Reproduce**
From the instructions in the [docs](https://bonfirenetworks.org/docs/hacking/)
1. `export FLAVOUR=cooperation WITH_DOCKER=total `
2. Running `just config` 

**Expected behavior**
I can spawn a dev environment.

**Screenshots**
```
Dependencies have diverged:
* dataloader (Hex package)
  the dependency dataloader 2.0.0

  > In deps/bonfire_api_graphql/mix.exs:
    {:dataloader, "~> 2.0.0", [app_properties: [optional_applications: [:ecto, :opentelemetry_process_propagator], applications: [:kernel, :stdlib, :elixir, :logger, :telemetry, :ecto, :opentelemetry_process_propagator], description: ~c"dataloader", modules: [Dataloader, Dataloader.Ecto, Dataloader.GetError, Dataloader.KV, Dataloader.Source, Dataloader.Source.Dataloader.Ecto, Dataloader.Source.Dataloader.KV], registered: [], vsn: ~c"2.0.0"], env: :prod, hex: "dataloader", override: true, repo: "hexpm"]}

  does not match the requirement specified

  > In deps/absinthe/mix.exs:
    {:dataloader, "~> 1.0.0", [env: :prod, hex: "dataloader", repo: "hexpm", optional: true]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
error: Recipe `cmd` failed on line 707 with exit code 1
error: Recipe `mix` failed on line 732 with exit code 1
error: Recipe `deps-get` failed on line 303 with exit code 1
error: Recipe `setup-dev` failed on line 128 with exit code 1
error: Recipe `flavour` failed on line 98 with exit code 1
error: Recipe `config` failed on line 89 with exit code 1
```

**Bonfire environment (please complete the following information):**
- Running with Docker? full
- Running env: env
- Running version (check on your instance's homepage): N/A
- Running flavour: cooperation
- Running any extra/forked extensions: N/A

**Device (please complete the following information):**
 - OS: Ubuntu Linux 22.4

**Comment by mayel** [comment]
Bonjour :) thanks for giving it a go! The `cooperation` flavour isn't being actively developed/maintained at the moment as we're focused on releasing 1.0 of the `classic` flavour. In any case, I've now pushed some fixes, so you if you pull the latest you should hopefully be able to run it, though please note you'll find broken UI and functionality in that flavour...

**Comment by DnzzL** [comment]
Thank you for the quick answer :pray: 

I understand, I was just a bit curious :wink: 

Now I have a new issue during `just config` after pulling:
```
* Updating iconify_ex (https://github.com/bonfire-networks/iconify_ex - origin/main)
error: Your local changes to the following files would be overwritten by checkout:
	assets/yarn.lock
Please commit your changes or stash them before you switch branches.
Aborting
** (Mix) Command "git --git-dir=.git checkout --quiet b88f58f49003be09bf20470293e67e25249b62f9" failed
error: Recipe `cmd` failed on line 708 with exit code 1
error: Recipe `mix` failed on line 733 with exit code 1
error: Recipe `deps-get` failed on line 304 with exit code 1
error: Recipe `setup-dev` failed on line 129 with exit code 1
error: Recipe `flavour` failed on line 99 with exit code 1
error: Recipe `config` failed on line 90 with exit code 1
```

**Comment by mayel** [comment]
Cool :) 
`just pre-update-deps` should deal with that.

**Comment by mayel** [comment]
@DnzzL were you able to get up and running?
