### ISSUE TITLE
Create demo site

### ISSUE THREAD

**Issue by loid345** [bonfire-networks/bonfire-app#82]
Hello. A very cool project with a great future, but there is no demo site. Can you deploy a demo site?

**Comment by mayel** [comment]
Thanks! We'll likely deploy a site soon, but since this is a social networking app, you'll only be able to browse the public-facing parts. It's still under heavy development so the best way to get a feel for the ecosystem would be to compile and run it yourself, even on your own machine. There's a docker-compose config available to help with that.

**Comment by volanar** [comment]
> Thanks! We'll likely deploy a site soon, but since this is a social networking app, you'll only be able to browse the public-facing parts. It's still under heavy development so the best way to get a feel for the ecosystem would be to compile and run it yourself, not necessarily on a server, your personal machine is fine. There's a docker-compose config available to help with that.

Thanks. Can you create a documentation section on bonfire ecosystem description and deployment?

**Comment by mayel** [comment]
@volanar this is still pre-pre-release, but you can try this: https://github.com/bonfire-ecosystem/bonfire-app/tree/release#running

**Comment by volanar** [comment]
I'm trying to set up a bonfire using docker according to https://github.com/bonfire-networks/bonfire-app/blob/main/docs/DEPLOY.md.
git clone git@gitlab.com: Bonfire / Server.git bonfire-backend is this correct?

**Comment by mayel** [comment]
Oops, that document wasn't ready to be committed (and bonfire isn't ready to be used outside of development and testing). I'll push a fix later today.

**Comment by mayel** [comment]
Hi @volanar I've updated the docs and the release branch at https://github.com/bonfire-networks/bonfire-app/tree/release 
Please let me know how it goes so we can improve the docs!

**Comment by volanar** [comment]
After running the make pre-config command, an error occurs
Makefile:51: *** missing separator.  Stop.

**Comment by mayel** [comment]
Oops, there was an unwanted carriage return. Should be fixed.

**Comment by ivanminutillo** [comment]
I am closing this issue for now
