### ISSUE TITLE
issues with hashtags

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#821]
- [x] hashtag at start of post not detected
- [x] hashtag should support _underscores

**Comment by mayel** [comment]
seems a milkdown.JS issue as this is what the backend receives: `"\\#test #hash\\_tag\n"` when you write `#test [#hash](http://localhost:4000/hashtag/hash)_tag` 

I could do some find/replace on server, like we already had to do for links and mentions:
```elixir
      |> Regex.replace(~r/<(http[^>]+)>/U, ..., " \\1 ")
      |> Regex.replace(~r/@<([^>]+)>/U, ..., " @\\1 ")
```

 but wonder if we can configure milkdown do give us what is actually written, so that this doesn't become too a messy (and likely incomplete) pile of workaround (which wouldn't apply if another wysiwyg editor or plaintext is used)

**Comment by ivanminutillo** [comment]
fixed
