### ISSUE TITLE
Bug: `just config` is broken when `WITH_DOCKER=total`.

### ISSUE THREAD

**Issue by fishinthecalculator** [bonfire-networks/bonfire-app#835]
**Describe the bug**
`just config` is broken when `WITH_DOCKER=total`.

**To Reproduce**
1. `export FLAVOUR=classic`
2. `export WITH_DOCKER=total`
3. `just config`
4. See error:

```
[...]

ERROR: Service "search" was pulled in as a dependency of service "web" but is not enabled by the active profiles. You may fix this by adding a common profile to "search" and "web".
error: Recipe `cmd` failed on line 733 with exit code 1
error: Recipe `mix` failed on line 758 with exit code 1
error: Recipe `deps-clean-data` failed on line 337 with exit code 1
error: Recipe `setup-dev` failed on line 128 with exit code 1
error: Recipe `flavour` failed on line 100 with exit code 1
error: Recipe `config` failed on line 91 with exit code 1
```

**Expected behavior**
`just config` should just work :) 

**Bonfire environment (please complete the following information):**
- Running with Docker? (see WITH_DOCKER env variable): total
- Running env: dev
- Running version (check on your instance's homepage): v0.9.6-beta.23
- Running flavour: classic

**Device (please complete the following information):**
 - OS: Linux Desktop

**Additional context**
There are two ways about this and I'm not sure of the best choice, maybe @chobeat can chime in:

1. to the `web` service in `docker-compose.yml` it gets added
```yaml
  profiles:
    - graph
    - search
```
2. some command line arguments are passed to the `docker compose` invokations in the `justfile`

What do you think?

**Comment by mayel** [comment]
Ah, I recently added the profiles to make the graph and search services optional (they can be included by running e.g. `just dev-run db graph search`) so I guess we need to remove them from `depends_on` though that may mean that those bg services may not be available yet when the app tries to use them right after starting...

**Comment by mayel** [comment]
Hmm maybe something like `docker compose up --no-deps search graph` would help?

**Comment by chobeat** [comment]
I'm receiving a related and similar error on the build step. @fishinthecalculator never got this one I think.

` ✔ db Pulled                                                                                                                                                                                                  1.4s 
[+] Building 0.0s (0/0)                                                                                                                                                                             docker:default
service search is required by web but is disabled. Can be enabled by profiles [search]
error: Recipe `build` failed on line 725 with exit code 1
error: Recipe `setup-dev` failed on line 127 with exit code 1
error: Recipe `flavour` failed on line 100 with exit code 1
error: Recipe `config` failed on line 91 with exit code 1
`
maybe it can help clarify the issue.

**Comment by mayel** [comment]
I've just commented the `depends_on` for now: https://github.com/bonfire-networks/bonfire-app/commit/b020ab7fe5508328e7edbc5d54793867eeb69602
hope this helps @chobeat @fishinthecalculator
