### ISSUE TITLE
Bug: can't see my own DMs to someone

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#848]

**Comment by aayushmau5** [comment]
Hi!

Can you elaborate on this issue further?

**Comment by mayel** [comment]
Hi! Well it's something we noticed when trying out the UI and probably needs to be investigated further to see if it's a backend bug (in https://github.com/bonfire-networks/bonfire_messages) or a frontend one (in  https://github.com/bonfire-networks/bonfire_ui_messages) and then a unit test should be added if none already is catching it before the bug is fixed.

**Comment by mayel** [comment]
hmm, on campground I can't see messages I've sent *nor* received

**Comment by mayel** [comment]
seems fixed, need to test in prod
