### ISSUE TITLE
Bug: "Something went wrong" while using the recipe for coop-cloud 

### ISSUE THREAD

**Issue by hl0dwig** [bonfire-networks/bonfire-app#854]
**Describe the bug**
After trying to deploy and start the app with abra, the app is running but I got "Something went wrong." on the website.
This is what I can see with the docker service logs --follow command:

```
20:14:00.628 request_id=F7RxB7sv9i-v06AAAFKR [warning] No current_user found, will fallback to looking for a current_user_id: %{
  reason: %Postgrex.Error{
      message: nil,
      postgres: %{
        code: :undefined_table,
        line: "1191",
        message: "relation \"category_tree\" does not exist",
        position: "5244",
        file: "parse_relation.c",
        unknown: "ERROR",
        severity: "ERROR",
        pg_code: "42P01",
        routine: "parserOpenTable"
      },
```

**To Reproduce**
Follow the steps from https://recipes.coopcloud.tech/bonfire
Comment the line `SENTRY_DSN=` in my .env file

**Expected behavior**
 App should start

**Bonfire environment (please complete the following information):**
- Running env: prod with docker image
- Running flavour: classic

**Comment by mayel** [comment]
That doesn't look like a RAM issue but rather a missing database migration. Could you please run `abra app run your.domain.name app bin/bonfire remote` followed by `Bonfire.Application.version` and then `Bonfire.Common.Repo.migrate` and post the output of that here?

**Comment by hl0dwig** [comment]
```
iex(bonfire@45734f59280b)1> Bonfire.Application.version
"0.9.8-beta.30"
iex(bonfire@45734f59280b)2> Bonfire.Common.Repo.migrate

22:19:21.591 [info] Migrate Bonfire.Common.Repo

22:19:21.605 [info] Migrations already up
Migration path: "/opt/app/lib/bonfire_umbrella-0.9.8-classic-beta.30/priv/repo"
Repo: Bonfire.Common.Repo
  Status    Migration ID    Migration Name
--------------------------------------------------
  up        20200523081010  citext
  up        20200523081012  init_pointers
  up        20200523081014  init_edges
  up        20200805090401  create_ap_tables
  up        20200817072952  create_oban_tables
  up        20200818094943  import_ap
  up        20200820094941  import_boundaries
  up        20200828094943  add_files
  up        20200828094944  import_me
  up        20200828094945  import_social
  up        20200828094946  import_social_graph
  up        20200828094947  import_posts
  up        20200828094948  import_messages
  up        20200924084501  tag
  up        20210102094944  import_shared_user
  up        20210402105128  ap_test_table
  up        20210410094945  profile_images
  up        20210412094946  fp
  up        20210618094945  peered_uri
  up        20210831134330  update_oban_jobs_table
  up        20210923093415  import_ap_activity
  up        20220208094942  import_invite_link
  up        20220304081300  care_closure
  up        20220408094940  settings
  up        20220428094200  add_files_mixin
  up        20220531084501  seen
  up        20220915052335  create_oban_peers
  up        20230202105128  add_object_boolean
  up        20230625152257  papertrail_versions
  up        20230703084501  alias
  up        20230822004944  replied_generated_total
  up        20230828094945  instance_admin_user
  up        20230829084501  sensitive
  up        20231019004944  boundaries_fixtures
  up        20231119004947  boundaries_users_fixtures
  up        20231201094945  files_refactor
  up        20231208134330  oban12
  up        20231212094945  settings_json
  up        20240109084501  hashtag
  up        20240110094945  gin_indexes
  up        20240121084501  label

[:ok]

```

**Comment by mayel** [comment]
Oops, I indeed don't see the migration in question listed there. It may be an oversight in that version, so I will trigger a new release, and  in the meantime you could try an older one eg. `bonfirenetworks/bonfire:0.9.8-beta.26-classic-amd64` (by changing `APP_DOCKER_IMAGE` in your .env)

**Comment by hl0dwig** [comment]
thanks for this @mayel now it... almost works ;-) the app is running, the website is showing up, but another error for another ticket again maybe: unable to sign up :-( but I'll check first if this problem hasn't been already seen and perhaps even wait for a new release ;-) 

anyway, can't wait to see more of it and again thanks for your quick support!

**Comment by mayel** [comment]
Ah there was a signup bug in a recent release, it may have been beta.26 :(  You could try the previous version (beta.23). Due to some refactors in progress it may take a couple days before a new release unfortunately. 
Thanks for your patience :)

**Comment by mayel** [comment]
Alright, that went smoother than expected and a new release is out :) Please let us know how you get on!

**Comment by hl0dwig** [comment]
Ok well I've tried this:

- I've changed the config file to get back this line `APP_DOCKER_IMAGE=bonfirenetworks/bonfire:latest-${FLAVOUR}-amd64`
- I've force deployed with this command `abra app deploy --force your-server.domain.name`
- I've tried to use the app... it was completely buggy, the console went crazy, information was wrong, ID were displayed in the trending topic, unable to load my timeline, website always trying to refresh :/ I didn't manage to catch a real error message
- I went back with 'APP_DOCKER_IMAGE=bonfirenetworks/bonfire:0.9.8-beta.23-classic-amd64' in the conf file
- I've force deployed again
- And everthing seems ok and working fine now
