### ISSUE TITLE
UX: Show a widget-based Dashboard to logged users instead of a timeline 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#860]
Timelines are ubiquitous in social networks and serve their purpose. But they must not be the unique way to interact with the network. Especially given bonfire's modularity and extensible approach - trying to fit everything into a timeline will end up being pretty limiting and frustrating. 
We want to investigate other approaches to the user dashboard (basically the homepage), where rather than the users being catapulted into a stream of posts, the dashboard is a configurable view made of widgets that summarize the most important activities, interactions, news from their network. 
Such summary can include recent signups (to welcome new users), a selection of posts and links that are seeing a lot of activity on the instance or in their network.
But depending on each user's preference, they may want to include a widget of most popular audio or songs, photos etc (leveraging the feed refactor/optimisation https://github.com/bonfire-networks/bonfire-app/issues/858 )
And of course with new extensions we will benefit from more widgets to include in the user dashboard page.
Here is a first implementation mockup:

<img width="1566" alt="Bonfire (8)" src="https://github.com/bonfire-networks/bonfire-app/assets/1852065/7cb29883-ff75-4870-b24d-5cc3b22bb9b7">

**Comment by mayel** [comment]
closing as done, can open other issues for creating additional widgets and/or a system for users to configure/add widgets
