### ISSUE TITLE
As an admin I'd like to be able to deactivate and delete a user account

### ISSUE THREAD

**Issue by hl0dwig** [bonfire-networks/bonfire-app#863]
**Is your feature request related to a problem? Please describe.**
I've forgotten to make signup on invite only on my instance of test, and some people have found the instance and have started to create accounts... how am I suppose to deactivate / delete their accounts?

**Describe the solution you'd like**
In the members list, I should be able to deactivate / delete a user account

**Describe alternatives you've considered**
Is it possible to it manually at least? I'm using the coop version (with abra tool)

**Comment by mayel** [comment]
You can disable their account (meaning block them for signing in any longer) in the instance settings members list (at `https://your_instance/settings/instance/members`), by selecting 'Block' in the menu next to a user and then 'Block instance-wide'. Will see about a command for actually deleting the user and data manually.

**Comment by hl0dwig** [comment]
Thanks for this information @mayel ,  it wasn't mentioned that this action would prevent people from logging in again :

"Super powers
You can enforce the block for all users of your instance. All local users will stop interact with gleda47@puabook.com or their content"

**Comment by mayel** [comment]
Yeah that message applies to remote users, we should change the text for local ones.

**Comment by mayel** [comment]
Updated the copy for local users:

<img width="541" alt="Screenshot 2024-02-25 at 20 59 39" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/ec498549-45ad-460e-b59d-b041db98ed57">


<img width="500" alt="Screenshot 2024-02-25 at 20 59 26" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/57ae007d-298a-45d5-b0bc-a086d437870a">

**Comment by mayel** [comment]
@hl0dwig do delete a user (+ their account + any other user profiles under that account + all their data such as posts) you can run this in the iex console: `"username_to_delete" |> Bonfire.Me.Users.get_current() |> Map.get(:account) |> Bonfire.Me.Accounts.enqueue_delete()`

**Comment by hl0dwig** [comment]
thanks for your help and quick answers and updates ;-)
