### ISSUE TITLE
UX: Improve Extensions settings

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#869]
Currently our extensions setting page is designed mostly for technical users (not a casuality it is currently put under "Advanced" section) 
But extensions on the opposite are mostly designed to allow an higher degree of customisation for non-technical users.
There are several layers of confusions atm:
- Bonfire extensions are listed together with external dependencies, schemas and low-level libraries.
- Extensions that can be enabled/disabled are mixed together with others that cannot be removed and it's not obvious what are the ones the user can configure
- Extensions names are not self-explanatory in most cases

Let's take as an example the (great) Obsidian extension page  

<img width="968" alt="Screenshot 2024-02-25 alle 16 14 55" src="https://github.com/bonfire-networks/bonfire-app/assets/1852065/969944fa-864f-417d-8224-30d1d20d682a">

I think we should:

- [x] List only the extensions that can be toggled and configured in the extension page and put all the other libraries / schema in a separate view (architecture, code overview, or similar)
- [x] Do not put the extensions page under the "Advanced" scary category, but more at the top of the page (extensions is one of the core value prop of bonfire and will be widely used )
- [x] #911
- [x] Add an extension settings page for those extensions that includes advanced config / settings #877

**Comment by mayel** [comment]
@ivanminutillo this could use some UI improvements but otherwise is basically done

**Comment by ivanminutillo** [comment]
I've did quite a bunch of work on the extensions settings. Now data schemas / external libraries are decoupled from the bonfire extensions. 
The extensions section occupies a specific part in the settings and enabled extensions (that contains settings or subpages) are displaied below the extension section (in the screenshot below)
 
<img width="314" alt="Screenshot 2024-07-01 alle 10 46 51" src="https://github.com/bonfire-networks/bonfire-app/assets/1852065/f0ddc90f-05ba-4e4a-858c-74d7c0a8f588">

I've restructured how users and admins can enable extension, using a toggle rather than a series of buttons, also decoupled the logic for users and admins in their respective sections - showing disabled toggles for extensions that only admins can enable - see screenshot.

<img width="979" alt="Screenshot 2024-07-01 alle 10 47 53" src="https://github.com/bonfire-networks/bonfire-app/assets/1852065/93d0c814-f7d1-4a56-9bd5-1458581af0bf">


I've also started drafting an internal page for each extension, if they contains specific settings and options to be configured (still a wip tough)

<img width="1239" alt="Screenshot 2024-07-01 alle 10 49 44" src="https://github.com/bonfire-networks/bonfire-app/assets/1852065/fc5bc537-3514-4083-a3af-dc753b45ee40">


I think there are still several needed improvements for creating a useful extensions settings:

- [ ] We should remove the distinction between User Interface extensions and feature extensions. This is a developer thing and those pages instead are meant to be used by users (it's not even clear for developers what's the diff at this point).
- [ ] Extensions that cannot be enabled by users should be listed somewhere else

**Comment by mayel** [comment]
Very nice! I've added the essential extensions seperetely at the bottom of the list for now:

<img width="1261" alt="Screenshot 2024-07-05 at 20 55 10" src="https://github.com/bonfire-networks/bonfire-app/assets/115318/e56e0c36-aa58-4e0b-801d-4ffcdbfb9ccd">

I'm thinking we can also show the license of each one, especially for the other page (which includes 3rd party libs)

**Comment by mayel** [comment]
Also we should create/document a way to indicate that a lib is a bonfire extension, to automatically filter which view/section they go in without depending on the name (since other people may create extensions that don't start with "bonfire_")

**Comment by mayel** [comment]
Also fixed the extension description and readme on details page

**Comment by mayel** [comment]
we have a few related open issues, such as #967 #990 but I think we can close this one?
