### ISSUE TITLE
Bug: reply remotely not working on demo site

### ISSUE THREAD

**Issue by adrigen** [bonfire-networks/bonfire-app#921]
**Describe the bug**
I hit reply on the demo site whilst logged out and there is an error once I submit my email

**To Reproduce**
1. Go to 'https://campground.bonfire.cafe/'
2. Click on 'reply' after a message
3. it asks for an email address enter 'bold.iron0109@fastmail.com'

**Expected behavior**
Get a white screen with 'Sorry, your actor or remote interaction URL was not found'

**Bonfire environment (please complete the following information):**
this is the online demo: https://campground.bonfire.cafe/pub/remote_interaction

**Device (please complete the following information):**
 - Device: pc
 - OS: mint 19
 - Browser [e.g. firefox, safari]
 - ff113

**Comment by mayel** [comment]
Hello, thanks for the report, please note that feature expects an fediverse / ActivityPub username rather than an email. Maybe we need to clarify that in the copy.

**Comment by adrigen** [comment]
there should be validation on the input, right?

**Comment by ivanminutillo** [comment]
yes @adrigen, and there are also some weird behaviours with phx-ignore on some fields (eg. the title disappear if the user focus or click other buttons)

**Comment by mayel** [comment]
An ActivityPub actor is indistinguishable from an email address though, until we actually try to query for it with WebFinge and not get a valid response, which is what that error message is saying.
