### ISSUE TITLE
Bug: Confirmation link not working on demo site

### ISSUE THREAD

**Issue by adrigen** [bonfire-networks/bonfire-app#922]
**Describe the bug**
Upon clicking the confirmation link there is an error.

This could be a result of slow delivery of email... in which case some communication about the time limit would be helpful... or a longer time limit.

**To Reproduce**
1. Sign up for a new account at https://campground.bonfire.cafe
2. Click on the link received in the "Welcome to Bonfire" email

**Expected behavior**
Get a message saying "Invalid confirmation link. Please request a new one below."
Every time. 

**Screenshots**
![Screenshot 2024-05-23 at 09-42-25 Campground · Campground](https://github.com/bonfire-networks/bonfire-app/assets/1256365/57b73bad-85b3-47a0-b8be-306a77fdad6d)

**Bonfire environment (please complete the following information):**
demo site https://campground.bonfire.cafe

**Device (please complete the following information):**
 - Device: pc
 - OS: mint 19
 - Browser ff113

**Comment by mayel** [comment]
seems to be working now
