### ISSUE TITLE
Add Roadmap to website

### ISSUE THREAD

**Issue by loid345** [bonfire-networks/bonfire-app#93]
Hello. I like your project. The potential of the platform is huge, the technology stack is perfect, the modularity of the phoenix framework project is cool! And in my opinion, users will be interested to know about the Bonfire roadmap in order to see the short-and long-term development plans of the project. You can specify both technical aspects of the implementation and organizational ones (add blog, forum, video, etc. functionality, integrate with matrix, create a non-profit organization for bonfire, create a channel on slack, mark up information about the platform on producthunt, etc.)

**Comment by mayel** [comment]
Hi @volanar, thanks for the encouragement and suggestions! We'll discuss this among the team but I think we'll at least publish some details about the roadmap soon...

**Comment by ivanminutillo** [comment]
We can close this issue as we're adding the roadmap to the upcoming website, thanks @loid345 for the suggestion :)
