### ISSUE TITLE
Problems When Posting And Commenting 

### ISSUE THREAD

**Issue by ctrxm** [bonfire-networks/bonfire-app#969]
Hi, I'm sorry, I want to convey an error in the latest bonfire by stating an error like this picture this happens on my website and on https://campground.bonfire.cafe/

Thank you 🤝

![Screenshot_2024-07-17-21-21-40-173_com android chrome-edit](https://github.com/user-attachments/assets/9ee5a0c3-2402-4721-b985-7affcc47eeb1)

**Comment by ctrxm** [comment]
> Thanks for the report, it was a recently introduced bug which is now fixed

Oh thank you, btw I have made a translation request for our language (Indonesian) and I have made a request at transifex, For that reason, I am ready to translate if you allow it

**Comment by mayel** [comment]
@ctrxm thanks! language now added in transifex
