### ISSUE TITLE
create custom generators for extensions

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#972]

**Comment by ctrxm** [comment]
![Screenshot_2024-07-17-21-21-40-173_com android chrome-edit](https://github.com/user-attachments/assets/79701a3d-d89f-4301-9b6d-739e8857ea1c)

Sir,pls update in Co-op / Abra There, when I installed with a clean server, an error like this still appeared

**Comment by mayel** [comment]
@ctrxm could you please try with the latest release?
