### ISSUE TITLE
integration with spam detection API services

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#995]
Integration with services like https://akismet.com to detect spammy signups/posts/comments, to auto-flag them for mods to look at:

<img width="1217" alt="Screenshot 2024-08-19 at 15 41 54" src="https://github.com/user-attachments/assets/b6b9ad64-ee11-44b0-bc02-5f852def6479">

**Comment by outlaw-dame** [comment]
What signals did you use for spam detection? As my understanding is some of the default signals that Akismet uses aren’t applicable to AP platforms and thus aren’t very strong nor reliable signals to detect spam

**Comment by mayel** [comment]
@outlaw-dame it's mostly based on user-provided text (including actor's username, bio, and post content) but also the email address, IP and user agent for local users (because this is also meant to catch local bot spam, not only federated spam).
